Feature: JSON stream writing
  This Feature tests the stream writing in Intens.
  A multitude of JSON-files created and then compared to the expected outcome.

  Scenario Outline: Compare folders with expected list
    When I run test_func
    Then the files <file> in folder reality and expected are the same

  Examples:
    | file                                           |
    | data_type_i.json                               |
    | data_typeScalar_i.json                         |
    | data_typeVector0_i.json                        |
    | data_typeVector1_i.json                        |
    | dataScalar_type_i.json                         |
    | dataScalar_typeScalar_i.json                   |
    | dataScalar_typeVector0_i.json                  |
    | dataScalar_typeVector1_i.json                  |
    | dataVector0_type_i.json                        |
    | dataVector0_typeScalar_i.json                  |
    | dataVector0_typeVector0_i.json                 |
    | dataVector0_typeVector1_i.json                 |
    | dataVector1_type_i.json                        |
    | dataVector1_typeScalar_i.json                  |
    | dataVector1_typeVector0_i.json                 |
    | dataVector1_typeVector1_i.json                 |
    | data_type_iScalar.json                         |
    | data_typeScalar_iScalar.json                   |
    | data_typeVector0_iScalar.json                  |
    | data_typeVector1_iScalar.json                  |
    | dataScalar_type_iScalar.json                   |
    | dataScalar_typeScalar_iScalar.json             |
    | dataScalar_typeVector0_iScalar.json            |
    | dataScalar_typeVector1_iScalar.json            |
    | dataVector0_type_iScalar.json                  |
    | dataVector0_typeScalar_iScalar.json            |
    | dataVector0_typeVector0_iScalar.json           |
    | dataVector0_typeVector1_iScalar.json           |
    | dataVector1_type_iScalar.json                  |
    | dataVector1_typeScalar_iScalar.json            |
    | dataVector1_typeVector0_iScalar.json           |
    | dataVector1_typeVector1_iScalar.json           |
    | data_type_iVector.json                         |
    | data_typeScalar_iVector.json                   |
    | data_typeVector0_iVector.json                  |
    | data_typeVector1_iVector.json                  |
    | dataScalar_type_iVector.json                   |
    | dataScalar_typeScalar_iVector.json             |
    | dataScalar_typeVector0_iVector.json            |
    | dataScalar_typeVector1_iVector.json            |
    | dataVector0_type_iVector.json                  |
    | dataVector0_typeScalar_iVector.json            |
    | dataVector0_typeVector0_iVector.json           |
    | dataVector0_typeVector1_iVector.json           |
    | dataVector1_type_iVector.json                  |
    | dataVector1_typeScalar_iVector.json            |
    | dataVector1_typeVector0_iVector.json           |
    | dataVector1_typeVector1_iVector.json           |
    | data_type_iVector1.json                        |
    | data_typeScalar_iVector1.json                  |
    | data_typeVector0_iVector1.json                 |
    | data_typeVector1_iVector1.json                 |
    | dataScalar_type_iVector1.json                  |
    | dataScalar_typeScalar_iVector1.json            |
    | dataScalar_typeVector0_iVector1.json           |
    | dataScalar_typeVector1_iVector1.json           |
    | dataVector0_type_iVector1.json                 |
    | dataVector0_typeScalar_iVector1.json           |
    | dataVector0_typeVector0_iVector1.json          |
    | dataVector0_typeVector1_iVector1.json          |
    | dataVector1_type_iVector1.json                 |
    | dataVector1_typeScalar_iVector1.json           |
    | dataVector1_typeVector0_iVector1.json          |
    | dataVector1_typeVector1_iVector1.json          |
    | data_type.json                                 |
    | data_typeScalar.json                           |
    | data_typeVector.json                           |
    | data_typeVector1.json                          |
    | dataScalar_type.json                           |
    | dataScalar_typeScalar.json                     |
    | dataScalar_typeVector.json                     |
    | dataScalar_typeVector1.json                    |
    | dataVector0_type.json                          |
    | dataVector0_typeScalar.json                    |
    | dataVector0_typeVector.json                    |
    | dataVector0_typeVector1.json                   |
    | dataVector1_type.json                          |
    | dataVector1_typeScalar.json                    |
    | dataVector1_typeVector.json                    |
    | dataVector1_typeVector1.json                   |
    | data.json                                      |
    | dataScalar.json                                |
    | dataVector.json                                |
    | dataVector1.json                               |
    | data_type_i-indented.json                      |
    | data_typeScalar_i-indented.json                |
    | data_typeVector0_i-indented.json               |
    | data_typeVector1_i-indented.json               |
    | dataScalar_type_i-indented.json                |
    | dataScalar_typeScalar_i-indented.json          |
    | dataScalar_typeVector0_i-indented.json         |
    | dataScalar_typeVector1_i-indented.json         |
    | dataVector0_type_i-indented.json               |
    | dataVector0_typeScalar_i-indented.json         |
    | dataVector0_typeVector0_i-indented.json        |
    | dataVector0_typeVector1_i-indented.json        |
    | dataVector1_type_i-indented.json               |
    | dataVector1_typeScalar_i-indented.json         |
    | dataVector1_typeVector0_i-indented.json        |
    | dataVector1_typeVector1_i-indented.json        |
    | data_type_iScalar-indented.json                |
    | data_typeScalar_iScalar-indented.json          |
    | data_typeVector0_iScalar-indented.json         |
    | data_typeVector1_iScalar-indented.json         |
    | dataScalar_type_iScalar-indented.json          |
    | dataScalar_typeScalar_iScalar-indented.json    |
    | dataScalar_typeVector0_iScalar-indented.json   |
    | dataScalar_typeVector1_iScalar-indented.json   |
    | dataVector0_type_iScalar-indented.json         |
    | dataVector0_typeScalar_iScalar-indented.json   |
    | dataVector0_typeVector0_iScalar-indented.json  |
    | dataVector0_typeVector1_iScalar-indented.json  |
    | dataVector1_type_iScalar-indented.json         |
    | dataVector1_typeScalar_iScalar-indented.json   |
    | dataVector1_typeVector0_iScalar-indented.json  |
    | dataVector1_typeVector1_iScalar-indented.json  |
    | data_type_iVector-indented.json                |
    | data_typeScalar_iVector-indented.json          |
    | data_typeVector0_iVector-indented.json         |
    | data_typeVector1_iVector-indented.json         |
    | dataScalar_type_iVector-indented.json          |
    | dataScalar_typeScalar_iVector-indented.json    |
    | dataScalar_typeVector0_iVector-indented.json   |
    | dataScalar_typeVector1_iVector-indented.json   |
    | dataVector0_type_iVector-indented.json         |
    | dataVector0_typeScalar_iVector-indented.json   |
    | dataVector0_typeVector0_iVector-indented.json  |
    | dataVector0_typeVector1_iVector-indented.json  |
    | dataVector1_type_iVector-indented.json         |
    | dataVector1_typeScalar_iVector-indented.json   |
    | dataVector1_typeVector0_iVector-indented.json  |
    | dataVector1_typeVector1_iVector-indented.json  |
    | data_type_iVector1-indented.json               |
    | data_typeScalar_iVector1-indented.json         |
    | data_typeVector0_iVector1-indented.json        |
    | data_typeVector1_iVector1-indented.json        |
    | dataScalar_type_iVector1-indented.json         |
    | dataScalar_typeScalar_iVector1-indented.json   |
    | dataScalar_typeVector0_iVector1-indented.json  |
    | dataScalar_typeVector1_iVector1-indented.json  |
    | dataVector0_type_iVector1-indented.json        |
    | dataVector0_typeScalar_iVector1-indented.json  |
    | dataVector0_typeVector0_iVector1-indented.json |
    | dataVector0_typeVector1_iVector1-indented.json |
    | dataVector1_type_iVector1-indented.json        |
    | dataVector1_typeScalar_iVector1-indented.json  |
    | dataVector1_typeVector0_iVector1-indented.json |
    | dataVector1_typeVector1_iVector1-indented.json |
    | data_type-indented.json                        |
    | data_typeScalar-indented.json                  |
    | data_typeVector-indented.json                  |
    | data_typeVector1-indented.json                 |
    | dataScalar_type-indented.json                  |
    | dataScalar_typeScalar-indented.json            |
    | dataScalar_typeVector-indented.json            |
    | dataScalar_typeVector1-indented.json           |
    | dataVector0_type-indented.json                 |
    | dataVector0_typeScalar-indented.json           |
    | dataVector0_typeVector-indented.json           |
    | dataVector0_typeVector1-indented.json          |
    | dataVector1_type-indented.json                 |
    | dataVector1_typeScalar-indented.json           |
    | dataVector1_typeVector-indented.json           |
    | dataVector1_typeVector1-indented.json          |
    | data-indented.json                             |
    | dataScalar-indented.json                       |
    | dataVector-indented.json                       |
    | dataVector1-indented.json                      |
    | data_type_iScalarVector.json                   |
    | data_type-iScalarVector.json                   |
    | data-iScalarVector.json                        |
    | data_type_iScalarVector-indented.json          |
    | data_type-iScalarVector-indented.json          |
    | data-iScalarVector-indented.json               |
    | data1.json                                     |
    | data1-indented.json                            |
    | data1_s1.json                                  |
    | data1_i1.json                                  |
    | data1_r1.json                                  |
    | data1Scalar.json                               |
    | data1_s1-indented.json                         |
    | data1_i1-indented.json                         |
    | data1_r1-indented.json                         |
    | data1Scalar-indented.json                      |
