{{- if .Values.imageCredentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: scim-registry
  labels:
    {{- include "scim.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
