#ifndef CONFIGURATOR_H
#define CONFIGURATOR_H

#include "parser/IdManager.h"
#include "gui/GuiElement.h"
#include "datapool/DataDictionary.h"
#include "xfer/XferDataItem.h"
#include "operator/FileStream.h"
#include "operator/MessageQueue.h"
#include "gui/GuiFieldgroupLine.h"
#include "gui/GuiLabel.h"
#include "gui/GuiVoid.h"
#include "gui/GuiNavigator.h"
#include "gui/GuiFolderGroup.h"
#include "app/HelpManager.h"
#include "gui/GuiPlotDataItem.h"
#include "plot/ListGraph.h"
#include "plot/Simpel.h"
#include "plot/PSPlot.h"
#include "gui/Gui2dPlot.h"
#include "gui/GuiList.h"
#include "gui/GuiForm.h"
#include "app/UiManager.h"
#include "operator/ReportStream.h"
#include "job/JobManager.h"
#include "gui/HardCopyTree.h"
#include "app/UserAttr.h"

class JobFunction;
class FunctionHandler;
class DataDictionary;
class Stream;

class GuiTable;
class GuiTableLine;
class GuiTableSize;
class GuiTableDataItem;
class GuiTableItem;
class GuiFolder;

class Configurator {
 public:
  Configurator(){}
  virtual ~Configurator(){}
 private:
  Configurator( const Configurator & );
  Configurator &operator=( const Configurator & );

 public:
  virtual bool dispatchPendingEvents() = 0;
  virtual bool setApplicationTitle( const std::string &title ) = 0;
  virtual bool end() = 0;
  virtual bool start(){ return true; }
  virtual bool beginDatapool()   { return true; }  // Cpp filestream-Umleitung
  virtual bool endDatapool()     { return true; }  // Cpp filestream-Umleitung
  virtual bool beginHelpfile()   { return true; }  //
  virtual bool beginLanguage()   { return true; }  //
  virtual bool beginStreamer()   { return true; }  //
  virtual bool   beginStream( const std::string &id ){ return true; }  //
  virtual bool   endStream()     { return true; }  //
  virtual bool beginUiManager()  { return true; }  //
  virtual bool beginOperator()   { return true; }  //
  virtual bool beginJob()        { return true; }  //
  virtual bool   beginFunc( const std::string &id ){ return true; }  //
  virtual bool   endFunc()       { return true; }  //
  virtual bool cppComment( const std::string &text ){ return true; }
  virtual std::string *convertString( std::string &s ){ return &s; }
  virtual std::string *convertSQLString( std::string &s ){ return &s; }
  virtual bool opCurrentIsoTime() = 0;
  virtual bool opCurrentIsoDate() = 0;
  virtual bool opCurrentIsoDatetime() = 0;

  // DataPool
  virtual bool newDataSet( const std::string &id ) = 0;
  virtual bool setDataSetItemValues( const std::string &id ) = 0;
  virtual bool setDataSetItemValues( const std::string &id, const double value ) = 0;
  virtual bool setDataSetItemValues( const std::string &id, const std::string &value ) = 0;
  virtual bool newColorSet( const std::string &id ) = 0;
  virtual bool setColorSetItemInvalid() = 0;
  virtual bool setColorSetItemAlways() = 0;
  virtual bool setColorSetItemLowerValue( int, double ) = 0;
  virtual bool setColorSetItemLowerXfer( int ) = 0;
  virtual bool setColorSetItemUpperValue( int, double ) = 0;
  virtual bool setColorSetItemUpperXfer( int ) = 0;
  virtual bool setColorSetItemLowerValue( int, std::string & ) = 0;
  virtual bool setColorSetItemUpperValue( int, std::string & ) = 0;
  virtual bool setColorSetItemColors( const std::string &bg, const std::string &fg ) = 0;
  virtual bool setColorSetItemColorsXfer(XferDataItem *bgXfer, XferDataItem *fgXfer) = 0;
  virtual bool setDictInitialise() = 0;
  virtual bool setDictIsGlobal( bool status ) = 0;
  virtual bool setDictWithoutTTrail() = 0;
  virtual bool setUserAttrNoDependencies() = 0;
  virtual bool setUserAttrLockable() = 0;
  virtual bool setUserAttrEditable() = 0;
  virtual bool setUserAttrOptional() = 0;
  virtual bool setUserAttrPersistent() = 0;
  virtual bool setUserAttrDbTransient( ) = 0;
  virtual bool setUserAttrClassname( const std::string &name ) = 0;
  virtual bool setUserAttrMaxOccurs( const int num ) = 0;
  virtual bool setUserAttrScalar() = 0;
  virtual bool setUserAttrCell() = 0;
  virtual bool setDataType( DataDictionary::DataType type ) = 0;
  virtual bool deleteUserAttr() = 0;
  virtual bool setUserAttr( UserAttr *attr ) = 0;
  virtual bool newUserAttr() = 0;
  virtual bool addDataVariable( const std::string &id ) = 0;
  virtual bool setIndexNum( const int num ) = 0;
  virtual bool unsetDictItemFolder() = 0;
  virtual bool setDictItemRange( double, double ) = 0;
  virtual bool setDictItemStep( double ) = 0;
  virtual bool setDictItemDefaultDimension( const int dim ) = 0;
  virtual bool setDataSetName( const std::string &name, bool bIndexed=false ) = 0;
  virtual bool setDataSetNoInvalidEntry() = 0;
  virtual bool setColorSetName( const std::string &name ) = 0;
  virtual bool setNoColorBit() = 0;
  virtual bool setDictItemFunction() = 0;
  virtual bool setDictItemFocusFunction() = 0;
  virtual bool setDictItemLabel( const std::string &label ) = 0;
  virtual bool setDictItemUnits( const std::string &units ) = 0;
  virtual bool setDictItemPattern( const std::string &pattern ) = 0;
  virtual bool setDictItemDate(UserAttr::STRINGtype type) = 0;
  virtual bool setDictItemHelpText( const std::string &helpText ) = 0;
  virtual bool setDictItemButton() = 0;
  virtual bool setDictItemSlider() = 0;
  virtual bool setDictItemProgress() = 0;
  virtual bool setDictItemToggle() = 0;
  virtual bool setDictItemRadio() = 0;
  virtual bool setDictItemCombobox() = 0;
  virtual bool setDictItemLabelType() = 0;
  virtual bool setDictItemClassName( const std::string &name ) = 0;
  virtual bool setDictItemPlaceholder( const std::string &text ) = 0;
  virtual bool setDictItemScalar() = 0;
  virtual bool setDictItemCell() = 0;
  virtual bool setDictItemHidden() = 0;
  virtual bool setDictItemPersistent() = 0;
  virtual bool setDictItemDbAttr( const std::string &name )=0;
  virtual bool setDictItemDbUnit( const std::string &name )=0;
  virtual bool setDictItemDbTransient( )=0;
  virtual bool setDictItemTag( const std::string &id, bool regist ) = 0;
  virtual bool setDictItemWheelEvent() = 0;
  virtual bool setDictStruct( const std::string &id, bool check = true ) = 0;
  virtual bool addStructureVariable( const std::string &id ) = 0;
  virtual bool addStructureDefinition( const std::string &id ) = 0;
  virtual bool copyStructureDefinition( const std::string &id ) = 0;
  virtual bool resetDictItem() = 0;
  virtual bool eraseParentName() = 0;
  // End Datapool
  //
  // HELPFILE
  virtual bool installHelpText( const std::string &filename ) = 0;
  virtual bool installHelpHTML( const std::string &filename ) = 0;
  virtual bool installHelpURL( const std::string &filename ) = 0;
  virtual bool installHelpKey( const std::string &anchor ) = 0;
  virtual bool installHelpCallback() = 0;
  virtual bool hideHelpMenu() = 0;
  // END HELPFILE
  //
  // STREAMER
  virtual Stream * newStream( const std::string &id ) = 0;
  virtual bool setStreamXMLFlag() = 0;
  virtual bool setStreamLatexFlag() = 0;
  virtual bool setStreamUrlFlag() = 0;
  virtual bool setStreamJSONFlag() = 0;
  virtual bool setStreamLocaleFlag() = 0;
  virtual bool setStreamFileFlag() = 0;
  virtual bool setStreamDelimiter(char delim) = 0;
  virtual bool setStreamIndent(int i) = 0;
  virtual bool setStreamerProcess( const std::string &processname ) = 0;
  virtual bool setStreamAppendOption() = 0;
  virtual bool setStreamNoGzOption() = 0;
  virtual bool setStreamHidden(bool yes) = 0;
  virtual bool setStreamTransient(bool yes) = 0;
  virtual bool resetStream() = 0;
  virtual bool stBeginGroup() = 0;
  virtual bool stEndGroup() = 0;
  virtual bool stNewXferDataItem( const std::string &dataItemID ) = 0;
  virtual bool resetDataItem() = 0;
  virtual bool stSetDataReference() = 0;
  virtual bool stSetVarDataReference() = 0;
  virtual bool pushDataItem() = 0;
  virtual bool getNextDataReference( const std::string &dataItemID ) = 0;
  virtual bool newDataItemIndex( const std::string &name ) = 0;
  virtual bool newDataItemIndex( int val ) = 0;
  virtual bool newDataItemIndex() = 0;
  virtual bool addIndexContainer( const std::string &indexID ) = 0;
  virtual bool addParameter( const bool optflag ) = 0;
  virtual bool addVarParameter() = 0;
  virtual bool addXMLParameter() = 0;
  virtual bool addJSONParameter() = 0;
  virtual bool withAllCycles() = 0;
  virtual bool setXMLSchema( const std::string & ) = 0;
  virtual bool setXMLNamespace( const std::string & ) = 0;
  virtual bool setXMLVersion( const std::string & ) = 0;
  virtual bool setXMLStylesheet( const std::string & ) = 0;
  virtual bool addXMLAttr( const std::string & ) = 0;
  virtual bool addMatrixParameter( const bool optflag, const char delimiter ) = 0;
  virtual bool addDatasetParameter() = 0;
  virtual bool addIndexParameter( const std::string &name, int length ) = 0;
  virtual bool addPlotGroupParameter( const std::string &plotId ) = 0;
  virtual bool setPlotGroupParameterTransparentBackground( bool transparent ) = 0;
  virtual bool setXRangeReal( const double value1, const double value2 ) = 0;
  virtual bool setXRangeDataRef() = 0;
  virtual bool addXMLPlotGroupStreamParameter( const std::string &pluginId ) = 0;
  virtual bool addToken( const std::string &token, int length ) = 0;
  virtual bool addGuiIndexParameter( const std::string &indexId ) = 0;
  virtual bool addSerializedFormParameter( const std::string &xslFile, const std::string &formId=std::string() ) = 0;
  virtual bool addSerializeFormId( const std::string &formId ) = 0;
  virtual bool addStringDateParameter(UserAttr::STRINGtype type, int length) = 0;
  // END STREAMER
  //
  // FIELD CONVERSION
  virtual bool resetConversionVariables() = 0;
  virtual bool setConversionVarLengthvalue( const int sign, const int value ) = 0;
  virtual bool setConversionVarPrec( const int precision ) = 0;
  virtual bool setConversionVarThousandsep( const bool showsep ) = 0;
  virtual bool setScaleFactor( double value )= 0;
  virtual bool setScaleFactor( XferDataItem *)= 0;
  virtual bool setScaleDivisor( double value )= 0;
  virtual bool setScaleDivisor( XferDataItem *)= 0;
  // FIELD OPTIONS
  virtual bool setFieldColSpan( int colspan, bool last=true ) = 0;
  virtual bool setFieldRowSpan( int rowspan, bool last=true ) = 0;
  virtual bool setFieldOrientation( GuiElement::Orientation orientation, bool last=true ) = 0;
  virtual bool setFieldRotation( int rotation, bool last=true ) = 0;
  virtual bool setFieldHelptextStream( const std::string &streamId, bool last=true ) = 0;
  virtual bool setFieldClass( const std::string &classname, bool last=true ) = 0;
  //
  // DATA-REFERENCE
  virtual bool getDataReference( const std::string &datavar ) = 0;
  virtual bool getDataReferenceStruct( const std::string &datavar ) = 0;
  //
  // UI_MANAGER
  virtual bool setFieldAttributes() = 0;
  virtual bool setFieldAttributes( const int flen, GuiElement::Alignment align, const bool tsep ) = 0;
  virtual bool setDataFieldLabel( const std::string &label ) = 0;
  virtual bool setDataFieldPixmap( const std::string &id) = 0;
  virtual bool setDataFieldSetGuiElementSize( const int width, const int height ) = 0;
  virtual bool setDataFieldScrollbar() = 0;
  virtual bool setDataFieldAutoScroll() = 0;
  virtual bool setDataFieldExpandable() = 0;
  virtual bool setDataFieldAttributes() = 0;
  virtual bool setFieldPrecision( const int precision ) = 0;
  virtual bool setVoidfieldSize( const int xvalue, const int yvalue ) = 0;
  virtual bool setVoidfieldDisplayPercentSize( const int xvalue, const int yvalue ) = 0;
  virtual bool uiNewXferDataItem( const std::string &id, bool clearIndexContainer = true ) = 0;
  virtual bool uiNewXferDataItemComplexReal( const std::string &id ) = 0;
  virtual bool uiNewXferDataItemComplexImag( const std::string &id ) = 0;
  virtual bool uiNewXferDataItemComplexAbs( const std::string &id ) = 0;
  virtual bool uiNewXferDataItemComplexArg( const std::string &id ) = 0;
  virtual bool uiNewXferDataItemFilestream( const std::string &id ) = 0;
  virtual bool uiSetDataReference() = 0;
  virtual bool setWildcard() = 0;
  virtual bool setLowerbound( const int indexConstant ) = 0;
  virtual bool setUpperbound( const int indexConstant ) = 0;
  virtual bool uiAddIndexContainer( const std::string &indexId ) = 0;
  virtual bool newFieldgroup( const std::string &fieldgroupId ) = 0;
  virtual bool hideFieldgroupIndexMenu() = 0;
  virtual bool hideFieldgroupIndexLabel() = 0;
  virtual bool setFieldgroupFunction() = 0;
  virtual bool setTitleHelpfile( const std::string &title ) = 0;
  virtual bool setTitleFieldgroup( const std::string &title, GuiElement::Alignment alignment ) = 0;
  virtual bool setTitlelist( const std::string &title, GuiElement::Alignment alignment) = 0;
  virtual bool setTitleForm( const std::string &title ) = 0;
  virtual bool setTitleListplot( const std::string &title ) = 0;
  virtual bool setTitleListgraph( const std::string &title ) = 0;
  virtual bool setTitleListgraphStream( const std::string &title ) = 0;
  virtual bool setTitleSimpel( const std::string &title ) = 0;
  virtual bool setTitlePsplot( const std::string &title ) = 0;
  virtual bool setTitleTable( const std::string &title, GuiElement::Alignment alignment ) = 0;
  virtual bool setTitleTableHorizontal( const std::string &title ) = 0;
  virtual bool setTitleTableVertical( const std::string &title ) = 0;
  virtual bool setTitleReportstream( const std::string &title ) = 0;
  virtual bool setHiddenReportstream() = 0;
  virtual bool setFieldgroupTableSize( const int tablesize, const int tablestep ) = 0;
  virtual bool setFieldgroupOrientation( GuiElement::Orientation orientation ) = 0;
  virtual bool setFieldgroupNavigation( GuiElement::Orientation orientation ) = 0;
  virtual bool setTablePosition( const int position ) = 0;
  virtual bool setTableIndexRange( const int start, const int end ) = 0;
  virtual bool setAlignment( GuiElement::Alignment alignment ) = 0;
  virtual bool setAlignFields() = 0;
  virtual bool newFieldgroupLine() = 0;
  virtual bool addArrowBar() = 0;
  virtual bool fieldgroupSetFrameOn() = 0;
  virtual bool fieldgroupSetUseRuler() = 0;
  virtual bool fieldgroupSetMargin( const int margin, const int spacing ) = 0;
  virtual bool fieldgroupSetGuiIndex(const std::string &indexId) = 0;
  virtual bool fieldgroupSetClass(const std::string &classname) = 0;
  virtual bool fieldgroupSetOverlay(const int xpos, const int ypos, const int width=-1, const int heigth=-1) = 0;
  virtual bool fieldgroupWithScrollBar() = 0;
  virtual bool fieldgroupSetAccordion(bool open=false) = 0;
  virtual bool fieldgroupSetWebApiPublish() = 0;
  virtual bool attachStringConstant( const std::string &labelstring, GuiElement::Alignment alignment ) = 0;
  virtual bool attachPixmap( const std::string &pixmapstring, GuiElement::Alignment alignment ) = 0;
  virtual bool attachVoidField() = 0;
  virtual bool attachColumnStretchField(int,int) = 0;
  virtual bool attachIndexField( const std::string &indexId, GuiElement::Alignment alignment ) = 0;
  virtual bool newDataField() = 0;
  virtual bool attachDataField() = 0;
  virtual bool attachNewPixmap() = 0;
  virtual bool setPixmapSize( int w, int h ) = 0;
  virtual bool attachFieldgroup( const std::string &name, GuiElement::Alignment alignment ) = 0;
  virtual bool attachThermo( const std::string &name, GuiElement::Alignment alignment ) = 0;
  virtual bool newList( const std::string &listId ) = 0;
  virtual bool attachList( const std::string &name, GuiElement::Alignment alignment ) = 0;
  virtual bool attachPlot2d( const std::string &name, GuiElement::Alignment alignment ) = 0;
  virtual bool setListTableSize( const int tablesize) = 0;
  virtual bool setListResizeable() = 0;
  virtual bool setListMultipleSelection() = 0;
  virtual bool setListFunction() = 0;
  virtual bool setListEnableSort( bool ) = 0;
  virtual bool withIndex( const int fieldlen ) = 0;
  virtual bool addListColumn( const std::string &columntext ) = 0;
  virtual bool addListColumn( XferDataItem *item ) = 0;
  virtual bool addListColumnToolTip() = 0;
  virtual bool addListColumnColor() = 0;
  virtual bool addListColumnOptional() = 0;
  virtual bool newIndexField( const std::string &indexId ) = 0;
  virtual bool setIndexfieldOrientation( GuiElement::Orientation orientation ) = 0;
  virtual bool setIndexfieldRange( const int start, const int end) = 0;
  virtual bool setIndexfieldStep( const int stepwidth ) = 0;
  virtual bool setIndexfieldFunction() = 0;
  virtual bool newGuiForm( const std::string &formId ) = 0;
  virtual bool formSetFunction( JobFunction * ) = 0;
  virtual bool form_hasCloseButton( bool ) = 0;
  virtual bool formUseSettings( bool ) = 0;
  virtual bool createButtonbar() = 0;
  virtual bool setMain() = 0;
  virtual bool setApplicationModal() = 0;
  virtual bool formSetMenuInstalled() = 0;
  virtual bool formSetScrollbarOn() = 0;
  virtual bool formSetScrollbarOff() = 0;
  virtual bool formSetPanedWindowOn() = 0;
  virtual bool formSetPanedWindowOff() = 0;
  virtual bool formSetUseRuler() = 0;
  virtual bool formSetExpandPolicy(GuiForm::DialogExpandPolicy expand_policy) = 0;
  virtual bool resetCycleButton() = 0;
  virtual bool setHelpkey( const std::string &anchorId ) = 0;
  virtual bool formSetHelptext( const std::string &text) = 0;
  virtual bool setButtonsPerLine( const int maxbuttons ) = 0;
  virtual bool containerSetScrollbarOn( GuiElement::Orientation, GuiElement::ScrollbarType sb ) = 0;
  virtual bool containerSetScrollbarOff() = 0;
  virtual bool containerSetPanedWindowOn() = 0;
  virtual bool containerSetPanedWindowOff() = 0;
  virtual bool containerSetFrameOn() = 0;
  virtual bool containerSetUseRuler() = 0;
  virtual bool containerSetTitle( const std::string &title ) = 0;
  virtual bool containerSetHelptext( const std::string &textstring ) = 0;
  virtual bool newContainer( GuiElement::Orientation horizontalVertical ) = 0;
  virtual bool popContainerStack() = 0;
  virtual bool cloneElement( const std::string &elementId ) = 0;
  virtual bool attachStandardWindow() = 0;
  virtual bool attachLogWindow() = 0;
  virtual bool configStandardWindow( bool ) = 0;
  virtual bool configLogWindow( bool ) = 0;
  virtual bool newSeparator(bool bcontainer=true, GuiElement::Alignment alignment=GuiElement::align_Default) = 0;
  virtual bool newVoid( int ) = 0;
  virtual bool newStretch( int ) = 0;
  virtual bool newListPlot( const std::string &listplotId ) = 0;
  virtual bool setCaptionStream( const std::string &streamId ) = 0;
  virtual bool addHGraph() = 0;
  virtual bool addGraph( const std::string &listplotitemId ) = 0;
  virtual bool checkGraph() = 0;
  virtual bool setXaxis() = 0;
  virtual bool listplot_setSize( int, int ) = 0;
  virtual bool listgraphSetAxisOriginY( const double originyaxis ) = 0;
  virtual bool listgraphSetLogX() = 0;
  virtual bool listgraphSetLogY() = 0;
  virtual bool setSameYRange() = 0;
  virtual bool addGraphItem() = 0;
  virtual bool setUnit( const std::string &unitsstring ) = 0;
  virtual bool plotaxisSetLabel( const std::string &labelstring ) = 0;
  virtual bool plotaxisSetLabel( XferDataItem* dataitem ) = 0;
  virtual bool plotAxisSetAnnoTitle( const std::string &labelstring ) = 0;
  virtual bool plotAxisSetAnnoAngle( double angle ) = 0;
  virtual bool plotaxisSetLabelStream( const std::string &streamId ) = 0;
  virtual bool plotaxisSetUnitStream( const std::string &streamId ) = 0;
  virtual bool plotaxisSetLineStyle( GuiPlotDataItem::eLineStyle linestyle ) = 0;
  virtual bool plot3dAxis_setScale( double min, double max ) = 0;
  virtual bool plot3dAxis_setScaleDataRef(XferDataItem *min_xfer, XferDataItem *max_xfer) = 0;
  virtual bool newSimpelPlot( const std::string &uniplotId ) = 0;
  virtual bool newPSStream( const std::string &streamId ) = 0;
  virtual bool newGui3dPlot( const std::string &plotId ) = 0;
  virtual bool newImage( const std::string &imgId ) = 0;
  virtual bool newLinePlot( const std::string &imgId ) = 0;
  virtual bool newThermo( const std::string &id ) = 0;
  virtual bool thermo_setRange( const double = 0, const double = 0 ) = 0;
  virtual bool thermo_setOffset( const double = 0 ) = 0;
  virtual bool thermo_hideLabel() = 0;
  virtual bool thermo_hideUnits() = 0;
  virtual bool thermo_setLabel( const std::string &label ) = 0;
  virtual bool thermo_setUnits( const std::string &label ) = 0;
  virtual bool thermo_setLabel( XferDataItem *item ) = 0;
  virtual bool thermo_setUnits( XferDataItem *item ) = 0;
  virtual bool thermo_setScaleFormat( const std::string &format ) = 0;
  virtual bool thermo_setColorSetName( const std::string &name ) = 0;
  virtual bool thermo_setColorScaleOption() = 0;
  virtual bool thermo_setColorScaleOptionScaled() = 0;
  virtual bool thermo_setXfer() = 0;
  virtual bool thermo_setOrientation( GuiElement::Orientation ) = 0;
  virtual bool thermo_setSize( int, int ) = 0;
  virtual bool thermo_setAlarmLevel( const double = 0 ) = 0;
  virtual bool thermo_setAlarmColorName( const std::string &name ) = 0;
  virtual bool thermo_setInverted(bool) = 0;
  virtual bool imageSetSocket( const std::string & ) = 0;
  virtual bool imageSetImageSettings( XferDataItem * ) = 0;
  virtual bool imageSetSize( const int width, const int height ) = 0;
  virtual bool newTimeTable( const std::string &imgId ) = 0;
  virtual bool timeTableSetSize( const int width, const int height ) = 0;
  virtual bool timeTableSetFromStringDateTime() = 0;
  virtual bool timeTableSetToStringDateTime() = 0;
  virtual bool timeTableSetToStringTime() = 0;
  virtual bool timeTableSetString() = 0;
  virtual bool plot3dSetMenuText( const std::string &menulabel ) = 0;
  virtual bool plot3dSetMenuInstalled( ) = 0;;
  virtual bool plot3dSetFooterStream( const std::string &streamId ) = 0;
  virtual bool plot3dSetFooterText( const std::string &stringConstant ) = 0;
  virtual bool plot3dSetSize( int height, int width ) = 0;
  virtual bool setPlotStyleBar() = 0;
  virtual bool setPlotStyleSurface() = 0;
  virtual bool setPlotStyleContour() = 0;
  virtual bool plot3dSetHeaderText( const std::string &headertext ) = 0;
  virtual bool plot3dSetHeaderStream( const std::string &streamId ) = 0;
  virtual bool putDataItemXaxis() = 0;
  virtual bool putDataItemYaxis() = 0;
  virtual bool newPlotDataItem() = 0;
  virtual bool plot3dRegisterIndexContainer() = 0;
  virtual bool putDataItemZaxis() = 0;
  virtual bool showPlot3dAnnotationLabels(bool xAxis) = 0;
  virtual bool setPlot3dMarker() = 0;
  virtual bool setPlot3dMarkerXAxis() = 0;
  virtual bool newXrtGraph( const std::string &plotId ) = 0;
  virtual bool xrtgraphSetMINMAX( bool show, int precision ) = 0;
  virtual bool xrtgraphSetAVG( bool show, int precision ) = 0;
  virtual bool xrtgraphSetRMS( bool show, int precision ) = 0;
  virtual bool xrtgraphSetMenuText( const std::string &menulabel ) = 0;
  virtual bool xrtgraphSetMenuInstalled( ) = 0;
  virtual bool xrtgraphSetFooterStream( const std::string &streamId ) = 0;
  virtual bool xrtgraphSetFooterText( const std::string &stringconstant ) = 0;
  virtual bool xrtgraphSetHeaderText( const std::string &headertext ) = 0;
  virtual bool xrtgraphSetHeaderStream( const std::string &streamId ) = 0;
  virtual bool xrtgraphSetPrintStyle( bool flag ) = 0;
  virtual bool addDataItem() = 0;
  virtual bool setAllCycles() = 0;
  virtual bool setOriginXAxis( const double originxaxis ) = 0;
  virtual bool setOriginYAxis( const double originyaxis ) = 0;
  virtual bool setLogX() = 0;
  virtual bool setLogY() = 0;
  virtual bool setConfigDialogStyle( int length ) = 0;
  virtual bool setWithScrollBar() = 0;
  virtual bool showAnnotationLabels() = 0;
  virtual bool setYPlotStyle( Gui2dPlot::eStyle style, Gui2dPlot::eAxisType axistype ) = 0;
  virtual bool setYPlotStyle( Gui2dPlot::eStyle style ) = 0;
  virtual bool xrtgraphRegisterIndexContainer() = 0;
  virtual bool xrtgraphSetLabel( const std::string &labelstring, Gui2dPlot::eAxisType axistype ) = 0;
  virtual bool xrtgraphSetLabelStream( const std::string &streamId, Gui2dPlot::eAxisType axistype ) = 0;
  virtual bool xrtgraphSetLabelDataRef( Gui2dPlot::eAxisType axistype ) = 0;
  virtual bool xrtgraphNewPlotDataItem() = 0;
  virtual bool setAxisType( Gui2dPlot::eAxisType axistype ) = 0;
  virtual bool withAnnotationOption( bool setvalue ) = 0;
  virtual bool withPlot3dAnnotationOption( bool setvalue ) = 0;
  virtual bool setAnnotationValues() = 0;
  virtual bool setAnnotationLabels() = 0;
  virtual bool new2dPlot( const std::string &plotId ) = 0;
  virtual bool addDummyItem() = 0;
  virtual bool plot2d_setScale( double min, double max,  Gui2dPlot::eAxisType axistype ) = 0;
  virtual bool plot2d_setScaleDataRef( Gui2dPlot::eAxisType axistype ) = 0;
  virtual bool plot2d_setScaleFormat( Gui2dPlot::eAxisType axistype, const std::string & ) = 0;
  virtual bool plot2d_setSize( int height, int width ) = 0;
  virtual bool plot2d_setAspectRatio(Gui2dPlot::eAxisType axistype, double value) = 0;
  virtual bool plot2d_setAspectRatioXfer(Gui2dPlot::eAxisType axistype) = 0;
  virtual bool plot2d_setAspectRatioReferenceAxis(Gui2dPlot::eAxisType axistype) = 0;
  virtual bool plot2dAddDataItemX() = 0;
  virtual bool plot2dAddDataItemY() = 0;
  virtual bool setPlot2dItemIsMarker() = 0;
  virtual bool setPlot2dItemColorSetName(const std::string& name) = 0;
  virtual bool setPlot2dMarker() = 0;
  virtual bool setPlot2dItemWildcardIndex(int wildcardIdx) = 0;
  virtual bool setPlot2dItemLegendHide(bool hide=true) = 0;
  virtual bool setPlot2dAxisHide( Gui2dPlot::eAxisType axistype ) = 0;
  virtual bool setPlot2dFunction() = 0;
  virtual bool setPlot2dColorSetName( const std::string &name ) = 0;
  virtual bool setNavigatorType(GuiNavigator::Type type) = 0;
  virtual bool newNavigator( const std::string &navigatorId ) = 0;
  virtual bool navigatorSetSize( const int width, const int height ) = 0;
  virtual bool navigatorSetToolTip( const std::string &toolTipTagId ) = 0;
  virtual bool navigatorAddColumn( const std::string &tagId, const std::string &labeltext, GuiNavigator::ColumnStyle colStyle ) = 0;
  virtual bool navigatorMultipleSelection() = 0;
  virtual bool navigatorSetExpandable() = 0;
  virtual bool navigatorSetScrollable() = 0;
  virtual bool navigatorSetCompareMode() = 0;
  virtual bool setRoot( const std::string &labeltext ) = 0;
  virtual bool setLastlevel( const double level ) = 0;
  virtual bool setFirstStructFolder( const double level ) = 0;
  virtual bool setAutoLevel() = 0;
  virtual bool setHideEmptyFolder() = 0;
  virtual bool addTransparentFolder( const std::string& hide_folder ) = 0;
  virtual bool setOpenLevels( const double level ) = 0;
  virtual bool newGuiScrolledText( const std::string &textwindowId ) = 0;
  virtual bool scrolledtextSetSize( const double lines, const double length ) = 0;
  virtual bool scrolledtextSetLabel( const std::string &labeltext ) = 0;
  virtual bool setWordwrap( bool setvalue ) = 0;
  virtual bool setFormatFortran() = 0;
  virtual bool scrolledtextSetPrintFilter( const std::string &filtertext ) = 0;
  virtual bool newGuiFolder( const std::string &folderId ) = 0;
  virtual bool attachFolder( const std::string &name, GuiElement::Alignment alignment ) = 0;
  virtual bool testNumberOfPages() = 0;
  virtual bool setButtonPlacement( GuiElement::Alignment alignment ) = 0;
  virtual bool setButtonText( GuiElement::ButtonType, const std::string &text )=0;
  virtual bool setLabelOrientation( GuiElement::Orientation orientation ) = 0;
  virtual bool setTabStretch() = 0;
  virtual bool setTabExpandable() = 0;
  virtual bool setTabMovable() = 0;
  virtual bool hideFolderButtons() = 0;
  virtual bool showAlwaysFolderButtons() = 0;
  virtual bool setFolderTabHidden(const std::string& hidden) = 0;
  virtual bool setFolderTabIcon(const std::string& iconname) = 0;
  virtual bool addFolderPage( const std::string &buttonlabel) = 0;
//  virtual bool uiFolderDefinitionFolderGroup() = 0;		// m_rep->i++;
  virtual bool registerFolderGroupId( const std::string &folderGroupId ) = 0;
  virtual bool addFolderGroupEntry( const std::string &folderGroupId ) = 0;
  virtual bool resetFunction() = 0;
  virtual bool addNamedElement( const std::string &pluginId ) = 0;
  virtual bool pluginAttachGuiElement( const std::string &labelstring ) = 0;
  virtual bool pluginSetLabel( const std::string &labelstring ) = 0;
  virtual bool setPluginXslFileName( const std::string &filename ) = 0;
  virtual bool newGuiTable( const std::string &tableId ) = 0;
  virtual bool attachTable( const std::string &name, GuiElement::Alignment alignment ) = 0;
  virtual bool setLabelAlignment( GuiElement::Alignment alignment ) = 0;
  virtual bool newTableSize() = 0;
  virtual bool setTableRowSize() = 0;
  virtual bool setTableColSize() = 0;
  virtual bool setTableOrientation( GuiElement::Orientation orientation ) = 0;
  virtual bool setTableNavigation( GuiElement::Orientation orientation ) = 0;
  virtual bool setTableFunction() = 0;
  virtual bool setTableAutoWidth() = 0;
  virtual bool tablesizeSetSize( const double size ) = 0;
  virtual bool tablesizeSetRange( int from, int to ) = 0;
  virtual bool tablesizeHideHeader() = 0;
  virtual bool hideTableIndexMenu() = 0;
  virtual bool setHorizontalPlacement( GuiElement::Alignment alignment ) = 0;
  virtual bool setVerticalPlacement( GuiElement::Alignment alignment ) = 0;
  virtual bool setTable() = 0;
  virtual bool addHorizontalLine( const std::string &label, GuiElement::Alignment alignment ) = 0;
  virtual bool tablelineCheck() = 0;
  virtual bool addTableDataItem() = 0;
  virtual bool addTableLabelItem( const std::string &label, GuiElement::Alignment alignment ) = 0;
  virtual bool addVerticalLine( const std::string &label, GuiElement::Alignment alignment ) = 0;
  virtual bool addTableLine( const std::string &label, GuiElement::Alignment alignment ) = 0;
  virtual bool addTableLineToolTip() = 0;
  virtual bool addTableLineColor() = 0;
  virtual bool addTableDataItemMatrix() = 0;
  virtual bool createNewMenu( const std::string &label ) = 0;
  virtual bool registerMenuId( const std::string &menuId ) = 0;
  virtual bool attachMenu() = 0;
  virtual bool getExistingMenu( const std::string &menuId ) = 0;
  virtual bool createNewSubMenu( const std::string &label ) = 0;
  virtual bool registerSubMenuId( const std::string &menuId ) = 0;
  virtual bool pulldownmenuSetLabel( const std::string &label ) = 0;
  virtual bool pulldownmenuSetHelptext( const std::string &helptext ) = 0;
  virtual bool formAttachMenu( const std::string &formId ) = 0;
  virtual bool getParentMenu() = 0;
  virtual bool addFormMenuButton( const std::string &formId, const std::string &label, bool toggle) = 0;
  virtual bool addFunctionMenuButton( const std::string &funcId, const std::string &label ) = 0;
  virtual bool addFunctionNavigatorMenuButton( const std::string &funcId, const std::string &label ) = 0;
  virtual bool getOpenMenu( bool with_remaining ) = 0;
  virtual bool resetPulldownmenu() = 0;
  virtual bool getSaveMenu( bool with_remaining ) = 0;
  virtual bool createFileButton( const std::string &name, const std::string &label ) = 0;
  virtual bool getHardcopyFolder( bool with_remaining ) = 0;
  virtual bool resetPrintfolder() = 0;
  virtual bool addHardcopyFolder( const std::string &label ) = 0;
  virtual bool getParentFolder() = 0;
  virtual bool printfolderAddSeparator() = 0;
  virtual bool addObject( const std::string &name, const std::string &label ) = 0;
  virtual bool newFormElementMenu( const std::string &list ) = 0;
  virtual bool newStructureMenu( const std::string &structure, unsigned int idx ) = 0;
  virtual bool newStructureDropMenu( const std::string &structure ) = 0;
  virtual bool newPlot2dMenuDescription() = 0;
  virtual bool addPlot2dMenuEntry( const std::string &entry )=0;
  // END UI_MANAGER
  //
  // OPERATOR
  virtual bool newSocket( const std::string& ) = 0;
  virtual bool newMsgQueue( const std::string& ) = 0;
  virtual bool newTimer( const std::string& ) = 0;
  virtual bool setUiUpdate( int interval ) = 0;
  virtual bool newBatchProcess( const std::string &processId, const std::string &cmd ) = 0;
  virtual bool newDaemonProcess( const std::string &processId, const std::string &cmd ) = 0;
  virtual bool newMatlabProcess( const std::string &processId ) = 0;
  virtual std::string *fifoCreateName( const std::string &comandId ) = 0;
  virtual bool newProcessGroup( const std::string &processgroupId ) = 0;
  virtual bool addProcessActionButton() = 0;
  virtual bool processgroupSetLabel( const std::string &labeltext ) = 0;
  virtual bool processgroupUnsetForm() = 0;
  virtual bool processgroupSetForm( const std::string &formId ) = 0;
  virtual bool processgroupSetMenuInstalled() = 0;
  virtual bool processgroupSetHelptext( const std::string &helptext ) = 0;
  virtual bool processgroupSetSilent() = 0;
  virtual bool processgroupSetLogOff() = 0;
  virtual bool processgroupNoDependencies() = 0;
  virtual bool processgroupAutoClearDependencies() = 0;
  virtual bool setOutputBasicStreams( const std::string &processId ) = 0;
  virtual bool setTargets() = 0;
  virtual bool newStream() = 0;
  virtual bool registerBasicStream() = 0;
  virtual bool getStream( const std::string &streamId, const std::string &fifoname ) = 0;
  virtual bool getSimpelPlot( const std::string &uniplotId ) = 0;
  virtual bool getPSStream( const std::string &psplotId ) = 0;
  virtual bool getStreamableGuiElement( const std::string &guiElemId ) = 0;
  virtual bool setTextWindow( const std::string &windowname ) = 0;
  virtual bool addInputStream( const std::string &streamId, const std::string &fifoname ) = 0;
  virtual bool addNewInputStream() = 0;
  virtual bool getStandardWindow() = 0;
  virtual bool resetScrolledtext() = 0;
  virtual bool opOLDfilestream( const std::string &streamId ) = 0;
  virtual bool opOLDfilestreamOptions() = 0;
  virtual bool opOLDreportstream( const std::string &reportstreamId ) = 0;
  virtual bool newFileStream( const std::string &fstreamId, const std::string &streamId ) = 0;
  virtual bool filestreamInstall() = 0;
  virtual bool installReportStream() = 0;
  virtual bool filestreamSetLabel( const std::string &labelname ) = 0;
  virtual bool filestream_SetDirname( const std::string &dirname ) = 0;
  virtual bool reportstream_SetDirname( const std::string &dirname ) = 0;
  virtual bool setFilter( const std::string &filtername ) = 0;
  virtual bool setProcess( const std::string &processname ) = 0;
  virtual bool setReset() = 0;
  virtual bool setReadOnly() = 0;
  virtual bool setWriteOnly() = 0;
  virtual bool filestreamSetLogOff() = 0;
  virtual bool setHidden() = 0;
  virtual bool setBinaryMode() = 0;
  virtual bool setExtension( const std::string &extension ) = 0;
  virtual bool newReportStream( const std::string &rstreamId,  const std::string &streamId ) = 0;
  virtual bool setLatexFlag() = 0;
  virtual bool setPrintFilter( const std::string &filterId) = 0;
  virtual bool setXmlFileFormat() = 0;
  virtual bool setXslFileName( const std::string &xslFile) = 0;
  virtual bool setTemplateFileName( const std::string &templateFile) = 0;
  virtual bool addProcessMenuButton( const std::string &processgroupId, const std::string &labeltext) = 0;
  virtual bool addTaskMenuButton( const std::string &taskId, const std::string &labeltext) = 0;
  // END OPERATOR
  //
  // JOB
  virtual int opSend() = 0;

  virtual bool socket_setMFM()=0;
  virtual bool socket_setDataref( XferDataItem *)=0;
  virtual bool socket_setThumbnail( XferDataItem *xfer, const int width, const int height )=0;
  virtual bool socket_setHost( const::std::string &host )=0;
  virtual bool socket_setHostXfer()=0;
  virtual bool socket_setPort( int port )=0;
  virtual bool socket_setPortXfer()=0;
  virtual bool socket_setHeader( const::std::string &header )=0;
  virtual bool socket_setOutStream( const::std::string &out_stream )=0;
  virtual bool socket_setInStream( const::std::string &in_stream )=0;
  virtual bool socket_setFunc( const::std::string &func )=0;
  virtual bool socket_setOnEos( const::std::string &func )=0;
  virtual bool socket_setOnViewAction( const::std::string &func )=0;

  virtual bool socketRequest_append() = 0;
  virtual bool socketRequest_setHeader( const::std::string &header ) = 0;
  virtual bool socketRequest_setOutStream( const::std::string &out_stream ) = 0;
  virtual bool socketRequest_setInStream( const::std::string &in_stream ) = 0;
  virtual bool socketRequest_setFunc( const::std::string &func ) = 0;

  // Message Queue
  virtual int  opRequest() = 0;
  virtual int  opPublish() = 0;
  virtual int  opSubscribe() = 0;
  virtual int  opSetMessageQueueHost() = 0;

  virtual bool transferData_setType(MessageQueue::Type type) = 0;
  virtual bool transferData_setMessageQueue( const::std::string &msgQueueId) = 0;
  virtual bool transferData_setHost( const::std::string &host )=0;
  virtual bool transferData_setHostXfer()=0;
  virtual bool transferData_setPort( int port )=0;
  virtual bool transferData_setPortXfer()=0;
  virtual bool transferData_setPortRequest( int port )=0;
  virtual bool transferData_setPortRequestXfer()=0;
  virtual bool transferData_setNoDependencies() = 0;
  virtual bool transferData_setTimeout(int timeout)=0;
  virtual bool transferData_setHeader( const::std::string &header )=0;
  virtual bool transferData_setOutStream( const::std::string &out_stream, int dep )=0;
  virtual bool transferData_setInStream( const::std::string &in_stream, int dep )=0;
  virtual bool transferData_addStream( const::std::string &out_stream, int dep )=0;
  virtual bool transferData_setOutStreams()=0;
  virtual bool transferData_setInStreams()=0;
  virtual bool transferData_addPlugin( const::std::string &out_plugin )=0;
  virtual bool transferData_setFunc( const::std::string &func )=0;

  virtual bool msgQueueHeader_append() = 0;
  virtual bool msgQueueHeader_setHeader( const::std::string &header ) = 0;
  virtual bool msgQueueHeader_setOutStream( const::std::string &out_stream, int dep ) = 0;
  virtual bool msgQueueHeader_setInStream( const::std::string &in_stream, int dep ) = 0;
  virtual bool msgQueueHeader_setOutStreams()=0;
  virtual bool msgQueueHeader_setInStreams()=0;
  virtual bool msgQueueHeader_setOutPlugins()=0;
  virtual bool msgQueueHeader_setPluginId( const::std::string &pluginId ) = 0;
  virtual bool msgQueueHeader_setFunc( const::std::string &func ) = 0;

  virtual bool transferData_setPlugin( const::std::string &pluginId) = 0;

  // Target Streams for Dependencies
  virtual bool targets_addInputStream( const::std::string &in_stream,
                                       int dependencies ) = 0;
  virtual bool targets_addOutputStream( const::std::string &out_stream,
                                        int dependencies ) = 0;
  virtual void targets_clearTargetStreams() = 0;
  virtual void targets_setAutoClear() = 0;
  virtual void targets_noDependencies() = 0;

  // Rest Service
  virtual int opRestServiceGet() = 0;
  virtual int opRestServiceDelete() = 0;
  virtual int opRestServicePut() = 0;
  virtual int opRestServicePost() = 0;
  virtual bool opRestServiceLogon() = 0;
  virtual bool opRestServiceJwtLogon() = 0;
  virtual bool opRestServiceLogoff() = 0;
  virtual bool restService_setPath( const::std::string &path )=0;
  virtual bool restService_setPathXfer()=0;
  virtual bool restService_setPathStream( const::std::string &pathStream )=0;
  virtual bool restService_setPathStream()=0;
  virtual bool restService_setFilterStream( const::std::string &filterStream )=0;
  virtual bool restService_setFilterStream()=0;
  virtual bool restService_setDataStream( const::std::string &dataStream )=0;
  virtual bool restService_setDataStream()=0;
  virtual bool restService_setResponseStream( const::std::string &responseStream )=0;
  virtual bool restService_setResponseStream()=0;
  virtual bool restService_setSetDbTimestamp()=0;
  virtual bool restService_setBaseUrlXfer()=0;
  virtual bool restService_setUsernameXfer()=0;
  virtual bool restService_setPasswordXfer()=0;
  virtual bool restService_setMessageXfer()=0;
  virtual bool restService_setJwtXfer()=0;

  virtual bool timer_setTimer( const std::string& timer) = 0;
  virtual bool timer_setMaxPendingFunctions( int nMax ) = 0;
  virtual bool timer_setPeriod( double p ) = 0;
  virtual bool timer_setPeriodXfer() = 0;
  virtual bool timer_setDelay( int p ) = 0;
  virtual bool timer_setDelayXfer() = 0;
  virtual bool opTimerStart() = 0;
  virtual bool opTimerStop() = 0;

  virtual bool newFunction( const std::string &id, bool registerId, bool setNamespace ) = 0;
  virtual bool func_setHighPriority( bool ) = 0;
  virtual bool setFuncSilent( bool ) = 0;
  virtual bool setFuncUpdateForms( bool ) = 0;
  virtual bool setFuncWebResponse(XferDataItem* xferReponse) = 0;
  virtual bool setFuncWebResponseProto() = 0;
  virtual int  opSetCurrentFormByWebApi( XferDataItem *xferdataitem ) = 0;
  virtual bool getAndResetNamespace() = 0;
  virtual bool getFunction( const std::string &funcid ) = 0;
  virtual bool newTask( const std::string &taskId, bool registerId ) = 0;
  virtual bool isNOTTaskImplemented() = 0;
  virtual bool setNamespace() = 0;
  virtual bool setNamespace( const std::string &funcId ) = 0;
  virtual bool addTaskActionButton() = 0;
  virtual bool taskSetLabel( const std::string &labeltext ) = 0;
  virtual bool taskUnsetForm() = 0;
  virtual bool taskSetForm( const std::string &formId ) = 0;
  virtual bool taskSetMenuInstalled() = 0;
  virtual bool taskSetHelptext( const std::string &helptext ) = 0;
  virtual bool taskSetLogOff() = 0;
  virtual bool taskSetSilent() = 0;
  virtual bool opPushVariable() = 0;
  virtual bool opSelectRows( const std::string &guiElementId, bool dataIsInt=false) = 0;
  virtual bool opGetSelection( const std::string &guiElementId ) = 0;
  virtual bool opGetSortCriteria( const std::string &guiElementId ) = 0;
  virtual bool opClearSelection( const std::string &guiElementId ) = 0;
  virtual int  opCopy( const std::string &streamId ) = 0;
  virtual int  opPaste( const std::string &streamId ) = 0;
  virtual bool opSetCycleNumber() = 0;
  virtual int  opPushNewValue() = 0;
  virtual bool opSetThis() = 0;
  virtual bool opSetBase() = 0;
  virtual bool assignThis() = 0;
  virtual bool assignFuncIndex() = 0;
  virtual bool assignFuncReason() = 0;
  virtual bool assignFuncArgs() = 0;
  virtual bool opSetSource() = 0;
  virtual bool opSetSource2() = 0;
  virtual bool newJobDataReference( const std::string &dataId, bool dataset=false,
				    UserAttr::STRINGtype type=UserAttr::string_kind_none ) = 0;
  virtual bool newJobDataReference2( const std::string &dataId, bool dataset=false,
				     UserAttr::STRINGtype type=UserAttr::string_kind_none ) = 0;
  virtual bool newJobVarDataReference() = 0;
  virtual bool pushDataRef() = 0;
  virtual bool popDataRef() = 0;
  virtual bool popDataItem() = 0;
  virtual bool jobdatarefAddVariableName(bool bParent=false) = 0;
  virtual bool incrementDatalevel() = 0;
  virtual bool extendDataReference( const std::string &dataId ) = 0;
  virtual bool convertToVar() = 0;
  virtual bool addIndex() = 0;
  virtual bool allowDataWildcards() = 0;
  virtual bool setDataWildcard() = 0;
  virtual bool opAssignIndex( const std::string &indexId ) = 0;
  virtual bool opAbort() = 0;
  virtual bool opExitIntens(bool force=false) = 0;
  virtual bool opBeep() = 0;
  virtual int  opResetError() = 0;
  virtual bool opNewCycle() = 0;
  virtual int  opDeleteCycle() = 0;
  virtual int  opClearCycle() = 0;
  virtual int  opFirstCycle() = 0;
  virtual int  opLastCycle() = 0;
  virtual int  opNextCycle() = 0;
  virtual bool opGoCycle() = 0;
  virtual int  opGetCycleName() = 0;
  virtual int  opSetCycleName() = 0;
  virtual int  opUpdateForms() = 0;
  virtual bool opSize() = 0;
  virtual bool opDataSize() = 0;
  virtual bool opIndex() = 0;
  virtual bool opIcon() = 0;
  virtual bool opCompare(bool bCycle) = 0;
  virtual bool opCompose() = 0;
  virtual bool opComposeNew() = 0;
  virtual bool opComposeIncreaseArg() = 0;
  virtual bool opAssignConsistency() = 0;
  virtual bool opClass(const std::string &guiElem, const std::string &className) = 0;
  virtual bool opSetResource(const std::string &key, const std::string &value, bool useValue) = 0;
  virtual bool opSetGuiFieldgroupRange( const std::string &fieldgroupId ) = 0;
  virtual bool opMessageBox(bool with_title=false) = 0;
  virtual int  opGuiElementMethod(std::string guiElem=std::string()) = 0;
  virtual int  opReplaceGuiElement( const std::string &fgIdOld, const std::string &fgIdNew ) = 0;
  virtual int  opEndOfFunction() = 0;
  virtual int  opBeginTransaction() = 0;
  virtual int  opCommitTransaction() = 0;
  virtual int  opAbortTransaction() = 0;
  virtual bool opAssignValue() = 0;
  virtual bool opIncrementValue() = 0;
  virtual bool opDecrementValue() = 0;
  virtual bool opAccumulateValue() = 0;
  virtual bool opActionResult() = 0;
  virtual int  opExecuteTask( const std::string &taskId ) = 0;
  virtual int  opExecuteFunction( const std::string &funcId ) = 0;
  virtual int  opExecuteFunction( XferDataItem *xferdataitem ) = 0;
  virtual int  opExecuteProcess( const std::string &processgroupId ) = 0;
  virtual int  opPluginInitialise( const std::string &pluginId ) = 0;
  virtual bool opExecutePlugin() = 0;
  virtual bool opPluginParameter() = 0;
  virtual int  opExecuteJobActionOpen( const std::string &filestreamId) = 0;
  virtual int  opGetFileName( const std::string &filestreamId ) = 0;
  virtual int  opGetBaseName( const std::string &filestreamId ) = 0;
  virtual int  opGetDirName( const std::string &filestreamId ) = 0;
  virtual int  opFileDialog( bool dironly=true ) = 0;
  virtual bool opFileDialog_setDirname( const std::string &dirname )=0;
  virtual bool opFileDialog_setDirnameXfer()=0;
  virtual bool opFileDialog_setOpenMode(bool open) = 0;
  virtual bool  opFileDialog_setFilter( const std::string &filtername) = 0;
  virtual int  opExecuteJobActionXMLXPath( const std::string &filestreamId,
					   XferDataItem *xferdataitemQry,
					   XferDataItem *xferdataitemDest) = 0;
  virtual int  fileOption_setXferFilename()=0;
  virtual int  fileOption_setXferBaseFilename()=0;
  virtual int  fileOption_setFilename(const std::string& filename)=0;
  virtual int  fileOption_setBaseFilename(const std::string& filename)=0;
  virtual int  opExecuteJobActionSave( const std::string &filestreamId) = 0;
  virtual int  opExecuteJobActionReport( ReportGen::Mode, const std::string &reportId ) = 0;
  virtual bool opParse( XferDataItem *xferdataitem )=0;
  virtual bool opParse( const std::string& filename )=0;
  virtual bool setSerializeType(AppData::SerializeType)=0;
  virtual bool setSerializeElement( const std::string &elemId )=0;
  virtual bool setSerializeOutputFilename( const std::string &filename ) = 0;
  virtual int  opSerializeGui()=0;
  virtual int  opSerializeForm( const std::string &formId )=0;
  virtual int  opSerializeGuiElement( const std::string &guiElemId )=0;
  virtual int  opWriteSettings()=0;
  virtual int  opMap(XferDataItem *xferdataitem, int nargs) = 0;
  virtual int  opMapForm( const std::string &formId ) = 0;
  virtual int  opMapFolder( const std::string &folderId, int nargs ) = 0;
  virtual int  opMapFolderGroup( const std::string &folderGroupId, GuiFolderGroup::OmitMap omit_map ) = 0;
  virtual int  opMapGuiElement( const std::string &guiElementId ) = 0;
  virtual int  opMapTableLine( const std::string &tableId ) = 0;
  virtual int  opUnmap() = 0;
  virtual int  opUnmapForm( const std::string &formId ) = 0;
  virtual int  opUnmapFolderGroup( const std::string &folderGroupId ) = 0;
  virtual int  opUnmapGuiElement( const std::string &guiElementId ) = 0;
  virtual int  opUnmapTableLine( const std::string &tableId ) = 0;
  virtual int  opVisible( XferDataItem *xferdataitem ) = 0;
  virtual int  opVisibleForm( const std::string &formId ) = 0;
  virtual int  opVisibleFolderGroup( const std::string &folderGroupId ) = 0;
  virtual int  opEditable() = 0;
  virtual int  opEditable( const std::string &guiElementId ) = 0;
  virtual int  opAllow() = 0;
  virtual int  opDisallow() = 0;
  virtual GuiForm      *getForm( const std::string &formId ) = 0;
  virtual JobTask      *getTask( const std::string &taskId ) = 0;
  virtual JobFunction  *jobGetFunction( const std::string &funcId ) = 0;
  virtual ProcessGroup *findProcessGroup( const std::string &pgId ) = 0;
  virtual int  opEnableGuiElement() = 0;
  virtual int  opDisableGuiElement() = 0;
  virtual int  opDisableDragGuiElement() = 0;
  virtual int  opSetEditable() = 0;
  virtual int  opSetEditableCycle() = 0;
  virtual int  opSetLocked() = 0;
  virtual int  opSetColor() = 0;
  virtual int  opSetColorBit() = 0;
  virtual int  opUnsetColorBit() = 0;
  virtual int  opSetDataTimestamp() = 0;
  virtual int  opSetStylesheet() = 0;
  virtual int  opSetStylesheet(const std::string &elementId) = 0;
  virtual int  opSetValueTimestamp() = 0;
  virtual GuiElement   *getNamedElement( const std::string &elementId ) = 0;
  virtual int  opUpdateGuiElement( const std::string &elementId ) = 0;
  virtual bool opClearValues() = 0;
  virtual bool opEraseValues() = 0;
  virtual bool opClearTextWindow( const std::string &textwindow ) = 0;
  virtual bool opPackValues( int ) = 0;
  virtual bool opAssignCorresponding() = 0;
  virtual bool opGetTimestamp() = 0;
  virtual bool opGetDbModified() = 0;
  virtual int  opSetDbTimestamp() = 0;
  virtual bool opGetClassname() = 0;
  virtual bool opGetNodename() = 0;
  virtual bool setElseAddress( int nextaddress ) = 0;
  virtual JobCodeOpIf    *opIfOperator() = 0;
  virtual bool opBranch() = 0;
  virtual bool setNextAddress( int nextaddress ) = 0;
  virtual JobCodeOpWhile *opWhileOperator() = 0;
  virtual int  opPushReal( const double realvalue ) = 0;
  virtual int  opPushInteger( const int intvalue ) = 0;
  virtual int  opPushSortOrder( const std::string &listId ) = 0;
  virtual int  opPushString( const std::string &stringconst ) = 0;
  virtual int  opPushEndOfLine() = 0;
  virtual int  opPushInvalid() = 0;
  virtual int  opPushOldValue() = 0;
  virtual int  opPushIndexNumber() = 0;
  virtual int  opPushColumn() = 0;
  virtual int  opPushRow() = 0;
  virtual int  opPushDiagramXPos() = 0;
  virtual int  opPushDiagramYPos() = 0;
  virtual int  opPushSortCriteria() = 0;
  virtual int  opPushError() = 0;
  virtual int  opPushReason( JobElement::CallReason reason ) = 0;
  virtual int  opPushCycle() = 0;
  virtual int  opPushMaxCycle() = 0;
  virtual int  opPushIndex( const std::string &indexId ) = 0;
  virtual int  opPushUnits() = 0;
  virtual int  opPushLabel() = 0;
  virtual bool opPushIndex() = 0;
  virtual bool opPushIndexOfLevel() = 0;
  virtual bool opEvalValid() = 0;
  virtual bool opEvalComplexValue() = 0;
  virtual bool opEvalComplexRealValue() = 0;
  virtual bool opEvalComplexImagValue() = 0;
  virtual bool opEvalAbsValue() = 0;
  virtual bool opEvalLengthValue() = 0;
  virtual bool opEvalSinValue() = 0;
  virtual bool opEvalCosValue() = 0;
  virtual bool opEvalTanValue() = 0;
  virtual bool opEvalASinValue() = 0;
  virtual bool opEvalACosValue() = 0;
  virtual bool opEvalATanValue() = 0;
  virtual bool opEvalATan2Value() = 0;
  virtual bool opEvalLogValue() = 0;
  virtual bool opEvalLog10Value() = 0;
  virtual bool opEvalSqrtValue() = 0;
  virtual bool opEvalArgValue() = 0;
  virtual bool opEvalChanged( const std::string &guiElemId, const bool filter ) = 0;
  virtual bool opRound() = 0;
  virtual bool opRound5() = 0;
  virtual bool opRound10() = 0;
  virtual bool opConfirm(bool cancelBtn) = 0;
  virtual bool opGetText() = 0;
  virtual bool opAdd() = 0;
  virtual bool opSub() = 0;
  virtual bool opMul() = 0;
  virtual bool opDiv() = 0;
  virtual bool opModulo() = 0;
  virtual bool opPower() = 0;
  virtual bool opNegate() = 0;
  virtual bool opGtr() = 0;
  virtual bool opGeq() = 0;
  virtual bool opLss() = 0;
  virtual bool opLeq() = 0;
  virtual bool opEql() = 0;
  virtual bool opNeq() = 0;
  virtual bool opAnd() = 0;
  virtual bool opOr() = 0;
  virtual bool opNot() = 0;
  virtual bool opPrint() = 0;
  virtual int opPrintLog() { return 0; }
  virtual int  opLog( const std::string &level ) = 0;
  virtual bool opLogMsg() = 0;
  virtual int  opSetError() = 0;
  virtual bool opSetErrorMsg() = 0;
  virtual bool opSetMessage() = 0;
  virtual bool opMessage() = 0;
  // END JOB
  //
  //
  // get-functions
  virtual DataReference         *getDataRef() = 0;
  virtual XferDataItem          *getDataItem() = 0;
  virtual XferDataItemIndex     *getDataItemIndex() = 0;
  virtual int                    getDataLevel() = 0;
  virtual FileStream            *getFileStream() = 0;
  virtual GuiElement            *getGuiElement() = 0;
  virtual GuiDataField          *getGuiDataField() = 0;
  virtual GuiVoid               *getGuiVoidField() = 0;
  virtual GuiIndex              *getGuiIndexField() = 0;
  virtual GuiFieldgroup         *getGuiFieldGroup() = 0;
  virtual GuiFieldgroupLine     *getGuiFieldgroupLine() = 0;
  virtual GuiLabel              *getGuiLabelField() = 0;
  virtual GuiForm               *getGuiForm() = 0;
  virtual GuiList               *getGuiList() = 0;
  virtual GuiScrolledText       *getGuiScrolledText() = 0;
  virtual HelpManager::HelpKey  *getHelpkey() = 0;
  virtual ListPlot              *getListplot() = 0;
  virtual ListGraph             *getListgraph() = 0;
  virtual GuiPlotDataItem       *getGuiPlotaxis() = 0;
  virtual Simpel                *getSimpel() = 0;
  virtual PSPlot                *getPsPlot() = 0;
  virtual PSPlot::PSStream      *getPsStream() = 0;
  virtual Gui3dPlot             *getPlot3d() = 0;
  virtual Gui2dPlot           *getGui2dPlot() = 0;
  virtual Gui2dPlot::PlotItem *getGuiPlotitem() = 0;
  virtual Gui2dPlot::PlotItem *getGuiXPlotitem() = 0;
  virtual GuiFolder             *getGuiFolder() = 0;
  virtual GuiTable              *getGuiTable() = 0;
  virtual GuiTableLine          *getGuiTableLine() = 0;
  virtual GuiTableSize          *getGuiTablesize() = 0;
  virtual GuiTableItem          *getGuiTableDataitem() = 0;
  virtual GuiTableItem          *getGuiTableItem() = 0;
  virtual Plugin                *getPlugin() = 0;
  virtual FileButtonList        *getFilemenulist() = 0;
  virtual HardCopyFolder        *getPrintfolder() = 0;
  virtual HardCopyListener      *getPrintobject() = 0;
  virtual Process               *getProcess() = 0;
  virtual ProcessGroup          *getProcessgroup() = 0;
  virtual Stream                *getStream() = 0;
  virtual int                    getIndexnum() = 0;
  virtual ReportStream          *getReportStream() = 0;
  virtual JobFunction           *getFunction() = 0;
  virtual JobTask               *getTask() = 0;
  virtual JobDataReference      *getJobDataRef() = 0;
  virtual JobAction             *getJobAction() = 0;
  virtual int                    getFunctionNextAddress() = 0;
  virtual void                   setFunctionHandler( FunctionHandler * )=0;
  // END get-functions
};

#endif
