
#ifndef INTERPRETERCONFIGURATOR_H
#define INTERPRETERCONFIGURATOR_H

#include <string>
#include "parser/Configurator.h"

#include "datapool/DataDictionary.h"
#include "operator/FileStream.h"
#include "gui/GuiFieldgroupLine.h"
#include "gui/GuiLabel.h"
#include "gui/GuiVoid.h"
#include "app/HelpManager.h"
#include "gui/Gui2dPlot.h"
#include "xfer/XferDataItem.h"

class JobManager;
class UserAttr;
class InterpreterConfigurator_Rep;

class InterpreterConfigurator: public Configurator
{
//=============================================================================//
// Constructor / Destructor                                                    //
//=============================================================================//
 public:
  InterpreterConfigurator();
  virtual ~InterpreterConfigurator();
 private:
  InterpreterConfigurator( const InterpreterConfigurator & );
  InterpreterConfigurator &operator=( const InterpreterConfigurator & );

//=============================================================================//
// Member Functions                                                            //
//=============================================================================//
 public:
  virtual bool dispatchPendingEvents();
  virtual bool setApplicationTitle( const std::string &title );
  virtual bool end();
  virtual bool opCurrentIsoTime();
  virtual bool opCurrentIsoDate();
  virtual bool opCurrentIsoDatetime();

  // DataPool
  virtual bool newDataSet( const std::string &id );
  virtual bool setDataSetItemValues( const std::string &id );
  virtual bool setDataSetItemValues( const std::string &id, const double value );
  virtual bool setDataSetItemValues( const std::string &id, const std::string &value );
  virtual bool newColorSet( const std::string &id );
  virtual bool setColorSetItemInvalid();
  virtual bool setColorSetItemAlways();
  virtual bool setColorSetItemLowerValue( int, double );
  virtual bool setColorSetItemLowerXfer( int );
  virtual bool setColorSetItemUpperValue( int, double );
  virtual bool setColorSetItemUpperXfer( int );
  virtual bool setColorSetItemLowerValue( int, std::string & );
  virtual bool setColorSetItemUpperValue( int, std::string & );
  virtual bool setColorSetItemColors( const std::string &bg, const std::string &fg );
  virtual bool setColorSetItemColorsXfer(XferDataItem *bgXfer, XferDataItem *fgXfer);
  virtual bool setDictInitialise();
  virtual bool setDictIsGlobal( bool status );
  virtual bool setDictWithoutTTrail();
  virtual bool setUserAttrNoDependencies();
  virtual bool setUserAttrLockable();
  virtual bool setUserAttrEditable();
  virtual bool setUserAttrOptional();
  virtual bool setUserAttrPersistent();
  virtual bool setUserAttrDbTransient( );
  virtual bool setUserAttrClassname( const std::string &name );
  virtual bool setUserAttrMaxOccurs( const int num );
  virtual bool setUserAttrScalar();
  virtual bool setUserAttrCell();
  virtual bool setDataType( DataDictionary::DataType type );
  virtual bool deleteUserAttr();
  virtual bool setUserAttr( UserAttr *attr );
  UserAttr *getUserAttr();
  virtual bool newUserAttr();
  virtual bool addDataVariable( const std::string &id );
  virtual bool setIndexNum( const int num );
  virtual bool unsetDictItemFolder();
  virtual bool setDictItemRange( double, double );
  virtual bool setDictItemStep( double );
  virtual bool setDictItemDefaultDimension( const int dim );
  virtual bool setDataSetName( const std::string &name, bool bIndexed=false );
  virtual bool setDataSetNoInvalidEntry();
  virtual bool setColorSetName( const std::string &name );
  virtual bool setNoColorBit();
  virtual bool setDictItemFunction();
  virtual bool setDictItemFocusFunction();
  virtual bool setDictItemLabel( const std::string &label );
  virtual bool setDictItemUnits( const std::string &units );
  virtual bool setDictItemPattern( const std::string &pattern );
  virtual bool setDictItemDate(UserAttr::STRINGtype type);
  virtual bool setDictItemHelpText( const std::string &helpText );
  virtual bool setDictItemButton();
  virtual bool setDictItemSlider();
  virtual bool setDictItemProgress();
  virtual bool setDictItemToggle();
  virtual bool setDictItemRadio();
  virtual bool setDictItemCombobox();
  virtual bool setDictItemLabelType();
  virtual bool setDictItemClassName( const std::string &name );
  virtual bool setDictItemPlaceholder( const std::string &text );
  virtual bool setDictItemScalar();
  virtual bool setDictItemCell();
  virtual bool setDictItemHidden();
  virtual bool setDictItemPersistent();
  virtual bool setDictItemDbAttr( const std::string &name );
  virtual bool setDictItemDbUnit( const std::string &name );
  virtual bool setDictItemDbTransient( );
  virtual bool setDictItemTag( const std::string &id, bool regist );
  virtual bool setDictItemWheelEvent();
  virtual bool setDictStruct( const std::string &id, bool check = true );
  virtual bool addStructureVariable( const std::string &id );
  virtual bool addStructureDefinition( const std::string &id );
  virtual bool copyStructureDefinition( const std::string &id );
  virtual bool resetDictItem();
  virtual bool eraseParentName();
  // End Datapool
  //
  // HELPFILE
  virtual bool installHelpText( const std::string &filename );
  virtual bool installHelpHTML( const std::string &filename );
  virtual bool installHelpURL( const std::string &filename );
  virtual bool installHelpKey( const std::string &anchor );
  virtual bool installHelpCallback();
  virtual bool hideHelpMenu();
  // END HELPFILE
  //
  // STREAMER
  virtual Stream * newStream( const std::string &id );
private:
  void stApplyOptions();
public:
  virtual bool setStreamXMLFlag();
  virtual bool setStreamLatexFlag();
  virtual bool setStreamUrlFlag();
  virtual bool setStreamJSONFlag();
  virtual bool setStreamLocaleFlag();
  virtual bool setStreamFileFlag();
  virtual bool setStreamDelimiter(char delim);
  virtual bool setStreamIndent(int i);
  virtual bool setStreamerProcess( const std::string &processname );
  virtual bool setStreamAppendOption();
  virtual bool setStreamNoGzOption();
  virtual bool setStreamHidden(bool yes);
  virtual bool setStreamTransient(bool yes);
  virtual bool resetStream();
  virtual bool stBeginGroup();
  virtual bool stEndGroup();
  virtual bool stNewXferDataItem( const std::string &dataItemID );
  virtual bool resetDataItem();
  virtual bool stSetDataReference();
  virtual bool stSetVarDataReference();
  virtual bool pushDataItem();
  virtual bool getNextDataReference( const std::string &dataItemID );
  virtual bool newDataItemIndex( const std::string &name );
  virtual bool newDataItemIndex( int val );
  virtual bool newDataItemIndex();
  virtual bool addIndexContainer( const std::string &indexID );
  virtual bool addParameter( const bool optflag );
  virtual bool addVarParameter();
  virtual bool addXMLParameter();
  virtual bool addJSONParameter();
  virtual bool setXMLSchema( const std::string & );
  virtual bool setXMLNamespace( const std::string & );
  virtual bool setXMLVersion( const std::string & );
  virtual bool setXMLStylesheet( const std::string & );
  virtual bool withAllCycles();
  virtual bool addXMLAttr( const std::string & );
  virtual bool addMatrixParameter( const bool optflag, const char delimiter );
  virtual bool addDatasetParameter();
  virtual bool addIndexParameter( const std::string &name, int length );
  virtual bool addPlotGroupParameter( const std::string &plotId );
  virtual bool setPlotGroupParameterTransparentBackground( bool transparent );
  virtual bool setXRangeReal( const double value1, const double value2 );
  virtual bool setXRangeDataRef();
  virtual bool addXMLPlotGroupStreamParameter( const std::string &pluginId );
  virtual bool addToken( const std::string &token, int length );
  virtual bool addGuiIndexParameter( const std::string &indexId );
  virtual bool addSerializedFormParameter( const std::string &xslFile, const std::string &formId="" );
  virtual bool addSerializeFormId( const std::string &formId );
  virtual bool addStringDateParameter(UserAttr::STRINGtype type, int length);
  // END STREAMER
  //
  // FIELD CONVERSION
  virtual bool resetConversionVariables();
  virtual bool setConversionVarLengthvalue( const int sign, const int value );
  virtual bool setConversionVarPrec( const int precision );
  virtual bool setConversionVarThousandsep( const bool showsep );
  virtual bool setScaleFactor( double value );
  virtual bool setScaleFactor( XferDataItem *);
  virtual bool setScaleDivisor( double value );
  virtual bool setScaleDivisor( XferDataItem *);
  // FIELD OPTIONS
  virtual bool setFieldColSpan( int colspan, bool last=true );
  virtual bool setFieldRowSpan( int rowspan, bool last=true );
  virtual bool setFieldOrientation( GuiElement::Orientation orientation, bool last=true );
  virtual bool setFieldRotation( int rotation, bool last=true );
  virtual bool setFieldHelptextStream( const std::string &streamId, bool last=true );
  virtual bool setFieldClass( const std::string &classname, bool last=true );
  //
  //
  virtual bool getDataReference( const std::string &datavar );
  virtual bool getDataReferenceStruct( const std::string &datavar );
  //
  // UI_MANAGER
  virtual bool setFieldAttributes();
  virtual bool setFieldAttributes( const int fieldlen, GuiElement::Alignment align, const bool tsep );
  virtual bool setDataFieldLabel( const std::string &label );
  virtual bool setDataFieldPixmap( const std::string &id );
  virtual bool setDataFieldSetGuiElementSize( const int width, const int height );
  virtual bool setDataFieldScrollbar();
  virtual bool setDataFieldAutoScroll();
  virtual bool setDataFieldExpandable();
  virtual bool setDataFieldAttributes();
  virtual bool setFieldPrecision( const int precision );
  virtual bool setVoidfieldSize( const int xvalue, const int yvalue );
  virtual bool setVoidfieldDisplayPercentSize( const int xvalue, const int yvalue );
  virtual bool uiNewXferDataItem( const std::string &id, bool clearIndexContainer = true );
  virtual bool uiNewXferDataItemComplexReal( const std::string &id );
  virtual bool uiNewXferDataItemComplexImag( const std::string &id );
  virtual bool uiNewXferDataItemComplexAbs( const std::string &id );
  virtual bool uiNewXferDataItemComplexArg( const std::string &id );
  virtual bool uiNewXferDataItemFilestream( const std::string &id );
  virtual bool uiSetDataReference();
  virtual bool setWildcard();
  virtual bool setLowerbound( const int indexConstant );
  virtual bool setUpperbound( const int indexConstant );
  virtual bool uiAddIndexContainer( const std::string &indexId );
  virtual bool newFieldgroup( const std::string &fieldgroupId );
  virtual bool hideFieldgroupIndexMenu();
  virtual bool hideFieldgroupIndexLabel();
  virtual bool setFieldgroupFunction();
  virtual bool setTitleHelpfile( const std::string &title );
  virtual bool setTitleFieldgroup( const std::string &title, GuiElement::Alignment alignment );
  virtual bool setTitlelist( const std::string &title, GuiElement::Alignment alignment );
  virtual bool setTitleForm( const std::string &title );
  virtual bool setTitleListplot( const std::string &title );
  virtual bool setTitleListgraph( const std::string &title );
  virtual bool setTitleListgraphStream( const std::string &title );
  virtual bool setTitleSimpel( const std::string &title );
  virtual bool setTitlePsplot( const std::string &title );
  virtual bool setTitleTable( const std::string &title, GuiElement::Alignment alignment );
  virtual bool setTitleTableHorizontal( const std::string &title );
  virtual bool setTitleTableVertical( const std::string &title );
  virtual bool setTitleReportstream( const std::string &title );
  virtual bool setHiddenReportstream();
  virtual bool setFieldgroupTableSize( const int tablesize, const int tablestep );
  virtual bool setFieldgroupOrientation( GuiElement::Orientation orientation );
  virtual bool setFieldgroupNavigation( GuiElement::Orientation orientation );
  virtual bool setTablePosition( const int position );
  virtual bool setTableIndexRange( const int start, const int end );
  virtual bool setAlignment( GuiElement::Alignment alignment );
  virtual bool setAlignFields();
  virtual bool newFieldgroupLine();
  virtual bool addArrowBar();
  virtual bool fieldgroupSetFrameOn();
  virtual bool fieldgroupSetUseRuler();
  virtual bool fieldgroupSetMargin( const int margin, const int spacing );
  virtual bool fieldgroupSetGuiIndex(const std::string &indexId);
  virtual bool fieldgroupSetClass(const std::string &classname);
  virtual bool fieldgroupSetOverlay(const int xpos, const int ypos, const int width=-1, const int heigth=-1);
  virtual bool fieldgroupWithScrollBar();
  virtual bool attachStringConstant( const std::string &labelstring, GuiElement::Alignment alignment );
  virtual bool attachPixmap( const std::string &pixmapstring, GuiElement::Alignment alignment );
  virtual bool attachVoidField();
  virtual bool attachColumnStretchField(int,int);
  virtual bool attachIndexField( const std::string &indexId, GuiElement::Alignment alignment );
  virtual bool newDataField();
  virtual bool attachDataField();
  virtual bool attachNewPixmap();
  virtual bool setPixmapSize( int w, int h );
  virtual bool attachFieldgroup( const std::string &name, GuiElement::Alignment alignment );
  virtual bool attachThermo( const std::string &name, GuiElement::Alignment alignment );
  virtual bool newList( const std::string &listId );
  virtual bool attachList( const std::string &name, GuiElement::Alignment alignment );
  virtual bool attachPlot2d( const std::string &name, GuiElement::Alignment alignment );
  virtual bool setListTableSize( const int tablesize);
  virtual bool setListResizeable();
  virtual bool setListMultipleSelection();
  virtual bool setListFunction();
  virtual bool setListEnableSort( bool );
  virtual bool withIndex( const int fieldlen );
  virtual bool addListColumn( const std::string &columntext );
  virtual bool addListColumn( XferDataItem *item );
  virtual bool addListColumnToolTip();
  virtual bool addListColumnColor();
  virtual bool addListColumnOptional();
  virtual bool newIndexField( const std::string &indexId );
  virtual bool setIndexfieldOrientation( GuiElement::Orientation orientation );
  virtual bool setIndexfieldRange( const int start, const int end);
  virtual bool setIndexfieldStep( const int stepwidth );
  virtual bool setIndexfieldFunction();
  virtual bool newGuiForm( const std::string &formId );
  virtual bool formSetFunction( JobFunction * );
  virtual bool form_hasCloseButton( bool );
  virtual bool formUseSettings( bool );
  virtual bool createButtonbar();
  virtual bool setMain();
  virtual bool setApplicationModal();
  virtual bool formSetMenuInstalled();
  virtual bool formSetScrollbarOn();
  virtual bool formSetScrollbarOff();
  virtual bool formSetPanedWindowOn();
  virtual bool formSetPanedWindowOff();
  virtual bool formSetUseRuler();
  virtual bool formSetExpandPolicy(GuiForm::DialogExpandPolicy expand_policy);
  virtual bool resetCycleButton();
  virtual bool setHelpkey( const std::string &anchorId );
  virtual bool formSetHelptext( const std::string &text);
  virtual bool setButtonsPerLine( const int maxbuttons );
  virtual bool containerSetScrollbarOn( GuiElement::Orientation o, GuiElement::ScrollbarType sb );
  virtual bool containerSetScrollbarOff();
  virtual bool containerSetPanedWindowOn();
  virtual bool containerSetPanedWindowOff();
  virtual bool containerSetFrameOn();
  virtual bool containerSetUseRuler();
  virtual bool containerSetTitle( const std::string &title );
  virtual bool containerSetHelptext( const std::string &textstring );
  virtual bool newContainer( GuiElement::Orientation horizontalVertical );
  virtual bool popContainerStack();
  virtual bool cloneElement( const std::string &elementId );
  virtual bool attachStandardWindow();
  virtual bool attachLogWindow();
  virtual bool configStandardWindow( bool );
  virtual bool configLogWindow( bool );
  virtual bool newSeparator(bool bcontainer=true, GuiElement::Alignment alignment=GuiElement::align_Default);
  virtual bool newVoid( int );
  virtual bool newStretch( int );
  virtual bool newListPlot( const std::string &listplotId );
  virtual bool setCaptionStream( const std::string &streamId );
  virtual bool addHGraph();
  virtual bool addGraph( const std::string &listplotitemId );
  virtual bool checkGraph();
  virtual bool setXaxis();
  virtual bool listplot_setSize( int, int );
  virtual bool listgraphSetAxisOriginY( const double originyaxis );
  virtual bool listgraphSetLogX();
  virtual bool listgraphSetLogY();
  virtual bool setSameYRange();
  virtual bool addGraphItem();
  virtual bool setUnit( const std::string &unitsstring );
  virtual bool plotaxisSetLabel( const std::string &labelstring );
  virtual bool plotaxisSetLabel( XferDataItem* dataitem );
  virtual bool plotAxisSetAnnoTitle( const std::string &labelstring );
  virtual bool plotAxisSetAnnoAngle( double angle );
  virtual bool plotaxisSetLabelStream( const std::string &streamId );
  virtual bool plotaxisSetUnitStream( const std::string &streamId );
  virtual bool plotaxisSetLineStyle( GuiPlotDataItem::eLineStyle linestyle );
  virtual bool plot3dAxis_setScale( double min, double max );
  virtual bool plot3dAxis_setScaleDataRef(XferDataItem *min_xfer, XferDataItem *max_xfer);
  virtual bool newSimpelPlot( const std::string &uniplotId );
  virtual bool newPSStream( const std::string &streamId );
  virtual bool newGui3dPlot( const std::string &plotId );
  virtual bool newImage( const std::string &imgId );
  virtual bool newLinePlot( const std::string &imgId );
  virtual bool newThermo( const std::string &id );
  virtual bool thermo_setRange( const double = 0, const double = 0 );
  virtual bool thermo_setOffset( const double = 0 );
  virtual bool thermo_hideLabel();
  virtual bool thermo_hideUnits();
  virtual bool thermo_setLabel( const std::string &label );
  virtual bool thermo_setUnits( const std::string &label );
  virtual bool thermo_setLabel( XferDataItem *item );
  virtual bool thermo_setUnits( XferDataItem *item );
  virtual bool thermo_setScaleFormat( const std::string &format );
  virtual bool thermo_setColorSetName( const std::string &name );
  virtual bool thermo_setColorScaleOption();
  virtual bool thermo_setColorScaleOptionScaled();
  virtual bool thermo_setXfer();
  virtual bool thermo_setSize( int, int );
  virtual bool thermo_setOrientation( GuiElement::Orientation );
  virtual bool thermo_setAlarmLevel( const double = 0 );
  virtual bool thermo_setAlarmColorName( const std::string &name );
  virtual bool thermo_setInverted(bool inv);
  virtual bool imageSetImageSettings( XferDataItem * );
  virtual bool imageSetSocket( const std::string & );
  virtual bool imageSetSize( const int width, const int height );
  virtual bool newTimeTable( const std::string &imgId );
  virtual bool timeTableSetFromStringDateTime();
  virtual bool timeTableSetToStringDateTime();
  virtual bool timeTableSetToStringTime();
  virtual bool timeTableSetString();
  virtual bool timeTableSetSize( const int width, const int height );
  virtual bool plot3dSetMenuText( const std::string &menulabel );
  virtual bool plot3dSetMenuInstalled();
  virtual bool plot3dSetFooterStream( const std::string &streamId );
  virtual bool plot3dSetFooterText( const std::string &stringConstant );
  virtual bool plot3dSetSize( int height, int width );
  virtual bool setPlotStyleBar();
  virtual bool setPlotStyleSurface();
  virtual bool setPlotStyleContour();
  virtual bool plot3dSetHeaderText( const std::string &headertext );
  virtual bool plot3dSetHeaderStream( const std::string &streamId );
  virtual bool putDataItemXaxis();
  virtual bool putDataItemYaxis();
  virtual bool newPlotDataItem();
  virtual bool plot3dRegisterIndexContainer();
  virtual bool setPlot3dMarker();
  virtual bool setPlot3dMarkerXAxis();
  virtual bool putDataItemZaxis();
  virtual bool showPlot3dAnnotationLabels(bool xAxis);
  virtual bool newXrtGraph( const std::string &plotId );
  virtual bool xrtgraphSetMINMAX( bool show, int precision );
  virtual bool xrtgraphSetAVG( bool show, int precision );
  virtual bool xrtgraphSetRMS( bool show, int precision );
  virtual bool xrtgraphSetMenuText( const std::string &menulabel );
  virtual bool xrtgraphSetMenuInstalled();
  virtual bool xrtgraphSetFooterStream( const std::string &streamId );
  virtual bool xrtgraphSetFooterText( const std::string &stringconstant );
  virtual bool xrtgraphSetHeaderText( const std::string &headertext );
  virtual bool xrtgraphSetHeaderStream( const std::string &streamId );
  virtual bool xrtgraphSetPrintStyle( bool flag );
  virtual bool addDataItem();
  virtual bool setAllCycles();
  virtual bool setOriginXAxis( const double originxaxis );
  virtual bool setOriginYAxis( const double originyaxis );
  virtual bool setLogX();
  virtual bool setLogY();
  virtual bool setConfigDialogStyle( int length );
  virtual bool setWithScrollBar();
  virtual bool showAnnotationLabels();
  virtual bool setYPlotStyle( Gui2dPlot::eStyle style, Gui2dPlot::eAxisType axistype );
  virtual bool setYPlotStyle( Gui2dPlot::eStyle style );
  virtual bool xrtgraphRegisterIndexContainer();
  virtual bool xrtgraphSetLabel( const std::string &labelstring, Gui2dPlot::eAxisType axistype );
  virtual bool xrtgraphSetLabelStream( const std::string &streamId, Gui2dPlot::eAxisType axistype );
  virtual bool xrtgraphSetLabelDataRef( Gui2dPlot::eAxisType axistype );
  virtual bool xrtgraphNewPlotDataItem();
  virtual bool setAxisType( Gui2dPlot::eAxisType axistype );
  virtual bool withAnnotationOption( bool setvalue );
  virtual bool withPlot3dAnnotationOption( bool setvalue );
  virtual bool setAnnotationValues();
  virtual bool setAnnotationLabels();
  virtual bool new2dPlot( const std::string &plotId );
  virtual bool addDummyItem();
  virtual bool plot2d_setScale( double min, double max,  Gui2dPlot::eAxisType axistype );
  virtual bool plot2d_setScaleDataRef( Gui2dPlot::eAxisType axistype );
  virtual bool plot2d_setScaleFormat( Gui2dPlot::eAxisType axistype, const std::string & );
  virtual bool plot2d_setSize( int height, int width );
  virtual bool plot2d_setAspectRatio(Gui2dPlot::eAxisType axistype, double value);
  virtual bool plot2d_setAspectRatioXfer(Gui2dPlot::eAxisType axistype);
  virtual bool plot2d_setAspectRatioReferenceAxis(Gui2dPlot::eAxisType axistype);
  virtual bool plot2dAddDataItemX();
  virtual bool plot2dAddDataItemY();
  virtual bool setPlot2dItemIsMarker();
  virtual bool setPlot2dItemColorSetName(const std::string& name);
  virtual bool setPlot2dMarker();
  virtual bool setPlot2dItemWildcardIndex( int wildcardIdx );
  virtual bool setPlot2dItemLegendHide(bool hide=true);
  virtual bool setPlot2dAxisHide( Gui2dPlot::eAxisType axistype );
  virtual bool setPlot2dFunction();
  virtual bool setPlot2dColorSetName( const std::string &name );
  virtual bool setNavigatorType(GuiNavigator::Type type);
  virtual bool newNavigator( const std::string &navigatorId );
  virtual bool navigatorSetSize( const int width, const int height );
  virtual bool navigatorSetToolTip( const std::string &toolTipTagId );
  virtual bool navigatorAddColumn( const std::string &tagId, const std::string &labeltext, GuiNavigator::ColumnStyle colStyle );
  virtual bool navigatorMultipleSelection();
  virtual bool navigatorSetExpandable();
  virtual bool navigatorSetScrollable();
  virtual bool navigatorSetCompareMode();
  virtual bool setRoot( const std::string &labeltext );
  virtual bool setLastlevel( const double level );
  virtual bool setFirstStructFolder( const double level );
  virtual bool setAutoLevel();
  virtual bool setHideEmptyFolder();
  virtual bool addTransparentFolder( const std::string& hide_folder );
  virtual bool setOpenLevels( const double level );
  virtual bool newGuiScrolledText( const std::string &textwindowId );
  virtual bool scrolledtextSetSize( const double lines, const double length );
  virtual bool scrolledtextSetLabel( const std::string &labeltext );
  virtual bool setWordwrap( bool setvalue );
  virtual bool setFormatFortran();
  virtual bool scrolledtextSetPrintFilter( const std::string &filtertext );
  virtual bool newGuiFolder( const std::string &folderId );
  virtual bool attachFolder( const std::string &name, GuiElement::Alignment alignment );
  virtual bool testNumberOfPages();
  virtual bool setButtonPlacement( GuiElement::Alignment alignment );
  virtual bool setButtonText( GuiElement::ButtonType, const std::string &text );
  virtual bool setLabelOrientation( GuiElement::Orientation orientation );
  virtual bool setTabStretch();
  virtual bool setTabExpandable();
  virtual bool setTabMovable();
  virtual bool hideFolderButtons();
  virtual bool showAlwaysFolderButtons();
  virtual bool setFolderTabHidden(const std::string& hidden);
  virtual bool setFolderTabIcon(const std::string& iconname);
  virtual bool addFolderPage( const std::string &buttonlabel);
//  virtual bool uiFolderDefinitionFolderGroup();		// m_rep->i++;
  virtual bool registerFolderGroupId( const std::string &folderGroupId );
  virtual bool addFolderGroupEntry( const std::string &folderGroupId );
  virtual bool resetFunction();
  virtual bool addNamedElement( const std::string &pluginId );
  virtual bool pluginAttachGuiElement( const std::string &labelstring );
  virtual bool pluginSetLabel( const std::string &labelstring );
  virtual bool setPluginXslFileName( const std::string &filename );
  virtual bool newGuiTable( const std::string &tableId );
  virtual bool attachTable( const std::string &name, GuiElement::Alignment alignment );
  virtual bool setLabelAlignment( GuiElement::Alignment alignment );
  virtual bool newTableSize();
  virtual bool setTableRowSize();
  virtual bool setTableColSize();
  virtual bool setTableOrientation( GuiElement::Orientation orientation );
  virtual bool setTableNavigation( GuiElement::Orientation orientation );
  virtual bool setTableFunction();
  virtual bool setTableAutoWidth();
  virtual bool tablesizeSetSize( const double size );
  virtual bool tablesizeSetRange( int from, int to );
  virtual bool tablesizeHideHeader();
  virtual bool hideTableIndexMenu();
  virtual bool setHorizontalPlacement( GuiElement::Alignment alignment );
  virtual bool setVerticalPlacement( GuiElement::Alignment alignment );
  virtual bool setTable();
  virtual bool addHorizontalLine( const std::string &label, GuiElement::Alignment alignment );
  virtual bool tablelineCheck();
  virtual bool addTableDataItem();
  virtual bool addTableLabelItem( const std::string &label, GuiElement::Alignment alignment );
  virtual bool addVerticalLine( const std::string &label, GuiElement::Alignment alignment );
  virtual bool addTableLine( const std::string &label, GuiElement::Alignment alignment );
  virtual bool addTableLineToolTip();
  virtual bool addTableLineColor();
  virtual bool addTableDataItemMatrix();
  virtual bool createNewMenu( const std::string &label );
  virtual bool registerMenuId( const std::string &menuId );
  virtual bool attachMenu();
  virtual bool getExistingMenu( const std::string &menuId );
  virtual bool createNewSubMenu( const std::string &label );
  virtual bool registerSubMenuId( const std::string &menuId );
  virtual bool pulldownmenuSetLabel( const std::string &label );
  virtual bool pulldownmenuSetHelptext( const std::string &helptext );
  virtual bool formAttachMenu( const std::string &formId );
  virtual bool getParentMenu();
  virtual bool addFormMenuButton( const std::string &formId, const std::string &label, bool toggle);
  virtual bool addFunctionNavigatorMenuButton( const std::string &funcId, const std::string &label );
  virtual bool addFunctionMenuButton( const std::string &funcId, const std::string &label );
  virtual bool getOpenMenu( bool with_remaining );
  virtual bool resetPulldownmenu();
  virtual bool getSaveMenu( bool with_remaining );
  virtual bool createFileButton( const std::string &name, const std::string &label );
  virtual bool getHardcopyFolder( bool with_remaining );
  virtual bool resetPrintfolder();
  virtual bool addHardcopyFolder( const std::string &label );
  virtual bool getParentFolder();
  virtual bool printfolderAddSeparator();
  virtual bool addObject( const std::string &name, const std::string &label );
  virtual bool newFormElementMenu( const std::string &list );
  virtual bool newStructureMenu( const std::string &structure, unsigned int idx );
  virtual bool newStructureDropMenu( const std::string &structure );
  virtual bool newPlot2dMenuDescription();
  virtual bool addPlot2dMenuEntry( const std::string &entry );
  // END UI_MANAGER
  //
  // OPERATOR
  virtual bool newSocket( const std::string& );
  virtual bool newMsgQueue( const std::string& );
  virtual bool newTimer( const std::string& );
  virtual bool setUiUpdate( int interval );
  virtual bool newBatchProcess( const std::string &processId, const std::string &cmd );
  virtual bool newDaemonProcess( const std::string &processId, const std::string &cmd );
  virtual bool newMatlabProcess( const std::string &processId );
  virtual std::string *fifoCreateName( const std::string &comandId );
  virtual bool newProcessGroup( const std::string &processgroupId );
  virtual bool addProcessActionButton();
  virtual bool processgroupSetLabel( const std::string &labeltext );
  virtual bool processgroupUnsetForm();
  virtual bool processgroupSetForm( const std::string &formId );
  virtual bool processgroupSetMenuInstalled();
  virtual bool processgroupSetHelptext( const std::string &helptext );
  virtual bool processgroupSetSilent();
  virtual bool processgroupSetLogOff();
  virtual bool processgroupNoDependencies();
  virtual bool processgroupAutoClearDependencies();
  virtual bool setOutputBasicStreams( const std::string &processId );
  virtual bool setTargets();
  virtual bool newStream();
  virtual bool registerBasicStream();
  virtual bool getStream( const std::string &streamId, const std::string &fifoname );
  virtual bool getSimpelPlot( const std::string &uniplotId );
  virtual bool getPSStream( const std::string &psplotId );
  virtual bool getStreamableGuiElement( const std::string &guiElemId );
  virtual bool setTextWindow( const std::string &windowname );
  virtual bool addInputStream( const std::string &streamId, const std::string &fifoname );
  virtual bool addNewInputStream();
  virtual bool getStandardWindow();
  virtual bool resetScrolledtext();
  virtual bool opOLDfilestream( const std::string &streamId );
  virtual bool opOLDfilestreamOptions();
  virtual bool opOLDreportstream( const std::string &reportstreamId );
  virtual bool newFileStream( const std::string &fstreamId, const std::string &streamId );
  virtual bool filestreamInstall();
  virtual bool installReportStream();
  virtual bool filestreamSetLabel( const std::string &labelname );
  virtual bool filestream_SetDirname( const std::string &dirname );
  virtual bool reportstream_SetDirname( const std::string &dirname );
  virtual bool setFilter( const std::string &filtername );
  virtual bool setProcess( const std::string &processname );
  virtual bool setReset();
  virtual bool setReadOnly();
  virtual bool setWriteOnly();
  virtual bool filestreamSetLogOff();
  virtual bool setHidden();
  virtual bool setBinaryMode();
  virtual bool setExtension( const std::string &extension );
  virtual bool newReportStream( const std::string &rstreamId,  const std::string &streamId );
  virtual bool setLatexFlag();
  virtual bool setPrintFilter( const std::string &filterId);
  virtual bool setXmlFileFormat();
  virtual bool setXslFileName( const std::string &xslFile);
  virtual bool setTemplateFileName( const std::string &templateFile);
  virtual bool addProcessMenuButton( const std::string &processgroupId, const std::string &labeltext);
  virtual bool addTaskMenuButton( const std::string &taskId, const std::string &labeltext);
  // END OPERATOR
  //
  // JOB
  virtual int opSend();

  virtual bool socket_setMFM();
  virtual bool socket_setDataref( XferDataItem * );
  virtual bool socket_setThumbnail( XferDataItem *xfer, const int width, const int height );
  virtual bool socket_setHost( const::std::string &host );
  virtual bool socket_setHostXfer();
  virtual bool socket_setPort( int port );
  virtual bool socket_setPortXfer();
  virtual bool socket_setHeader( const::std::string &header );
  virtual bool socket_setOutStream( const::std::string &out_stream );
  virtual bool socket_setInStream( const::std::string &in_stream );
  virtual bool socket_setFunc( const::std::string &func );
  virtual bool socket_setOnEos( const::std::string &func );
  virtual bool socket_setOnViewAction( const::std::string &func );

  /** add new server request data to request list*/
  virtual bool socketRequest_append();
  /** add header request data*/
  virtual bool socketRequest_setHeader( const::std::string &header );
  /** add request stream request data*/
  virtual bool socketRequest_setOutStream( const::std::string &out_stream );
  /** add response stream  request data*/
  virtual bool socketRequest_setInStream( const::std::string &in_stream );
  /** add function request data*/
  virtual bool socketRequest_setFunc( const::std::string &func );

  // Message Queue
  virtual int  opRequest();
  virtual int  opPublish();
  virtual int  opSubscribe();
  virtual int  opSetMessageQueueHost();

  virtual bool transferData_setType(MessageQueue::Type type);
  virtual bool transferData_setMessageQueue( const::std::string &msgQueueId);
  virtual bool transferData_setHost( const::std::string &host );
  virtual bool transferData_setHostXfer();
  virtual bool transferData_setPort( int port );
  virtual bool transferData_setPortXfer();
  virtual bool transferData_setPortRequest( int port );
  virtual bool transferData_setPortRequestXfer();
  virtual bool transferData_setNoDependencies();
  virtual bool transferData_setTimeout(int timeout);
  virtual bool transferData_setHeader( const::std::string &header );
  virtual bool transferData_setOutStream( const::std::string &out_stream, int dep );
  virtual bool transferData_setInStream( const::std::string &in_stream, int dep );
  virtual bool transferData_addStream( const::std::string &out_stream, int dep );
  virtual bool transferData_setOutStreams();
  virtual bool transferData_setInStreams();
  virtual bool transferData_addPlugin( const::std::string &out_plugin );
  virtual bool transferData_setFunc( const::std::string &func );

  virtual bool msgQueueHeader_append();
  virtual bool msgQueueHeader_setHeader( const::std::string &header );
  virtual bool msgQueueHeader_setOutStream( const::std::string &out_stream, int dep );
  virtual bool msgQueueHeader_setInStream( const::std::string &in_stream, int dep );
  virtual bool msgQueueHeader_setOutStreams();
  virtual bool msgQueueHeader_setInStreams();
  virtual bool msgQueueHeader_setOutPlugins();
  virtual bool msgQueueHeader_setPluginId( const::std::string &pluginId );
  virtual bool msgQueueHeader_setFunc( const::std::string &func );

  virtual bool transferData_setPlugin( const::std::string &pluginId);

  // Target Streams for Dependencies
  virtual bool targets_addInputStream( const::std::string &in_stream,
                                       int dependencies );
  virtual bool targets_addOutputStream( const::std::string &out_stream,
                                        int dependencies );
  virtual void targets_clearTargetStreams();
  virtual void targets_setAutoClear();
  virtual void targets_noDependencies();

  // Rest Service
private:
  void opRestServiceCheckPath();
public:
  virtual int opRestServiceGet();
  virtual int opRestServiceDelete();
  virtual int opRestServicePut();
  virtual int opRestServicePost();
  virtual bool opRestServiceLogon();
  virtual bool opRestServiceJwtLogon();
  virtual bool opRestServiceLogoff();
  virtual bool restService_setPath( const::std::string &path );
  virtual bool restService_setPathXfer();
  virtual bool restService_setPathStream( const::std::string &path_stream );
  virtual bool restService_setPathStream();
  virtual bool restService_setFilterStream( const::std::string &filterStream );
  virtual bool restService_setFilterStream();
  virtual bool restService_setDataStream( const::std::string &dataStream );
  virtual bool restService_setDataStream();
  virtual bool restService_setResponseStream( const::std::string &responseStream );
  virtual bool restService_setResponseStream();
  virtual bool restService_setSetDbTimestamp();
  virtual bool restService_setBaseUrlXfer();
  virtual bool restService_setUsernameXfer();
  virtual bool restService_setPasswordXfer();
  virtual bool restService_setMessageXfer();
  virtual bool restService_setJwtXfer();

  virtual bool timer_setTimer( const::std::string &timer );
  virtual bool timer_setMaxPendingFunctions( int nMax );
  virtual bool timer_setPeriod( double p );
  virtual bool timer_setPeriodXfer();
  virtual bool timer_setDelay( int d );
  virtual bool timer_setDelayXfer();
  virtual bool opTimerStart();
  virtual bool opTimerStop();

  virtual bool newFunction( const std::string &id, bool registerId, bool setNamespace );
  virtual bool func_setHighPriority( bool );
  virtual bool setFuncSilent( bool );
  virtual bool setFuncUpdateForms( bool );
  virtual bool setFuncWebResponse(XferDataItem *xferResponse);
  virtual bool setFuncWebResponseProto();
  virtual int opSetCurrentFormByWebApi( XferDataItem *xferdataitem );
  virtual bool getAndResetNamespace();
  virtual bool getFunction( const std::string &funcid );
  virtual bool newTask( const std::string &taskId, bool registerId );
  virtual bool isNOTTaskImplemented();
  virtual bool setNamespace();
  virtual bool setNamespace( const std::string &funcId );
  virtual bool addTaskActionButton();
  virtual bool taskSetLabel( const std::string &labeltext );
  virtual bool taskUnsetForm();
  virtual bool taskSetForm( const std::string &formId );
  virtual bool taskSetMenuInstalled();
  virtual bool taskSetHelptext( const std::string &helptext );
  virtual bool taskSetLogOff();
  virtual bool taskSetSilent();
  virtual bool opPushVariable();
  virtual bool opSelectRows( const std::string &guiElementId, bool dataIsInt=false );
  virtual bool opGetSelection( const std::string &guiElementId );
  virtual bool opGetSortCriteria( const std::string &guiElementId );
  virtual bool opClearSelection( const std::string &guiElementId );
  virtual int  opCopy( const std::string &streamId );
  virtual int  opPaste( const std::string &streamId );
  virtual bool opSetCycleNumber();
  virtual int  opPushNewValue();
  virtual bool opSetThis();
  virtual bool opSetBase();
  virtual bool assignThis();
  virtual bool assignFuncIndex();
  virtual bool assignFuncReason();
  virtual bool assignFuncArgs();
  virtual bool opSetSource();
  virtual bool opSetSource2();
  virtual bool newJobDataReference( const std::string &dataId, bool dataset=false,
				    UserAttr::STRINGtype type=UserAttr::string_kind_none );
  virtual bool newJobDataReference2( const std::string &dataId, bool dataset=false,
				    UserAttr::STRINGtype type=UserAttr::string_kind_none );
  virtual bool newJobVarDataReference();
  virtual bool pushDataRef();
  virtual bool popDataRef();
  virtual bool popDataItem();
  virtual bool jobdatarefAddVariableName(bool bParent=false);
  virtual bool incrementDatalevel();
  virtual bool extendDataReference( const std::string &dataId );
  virtual bool convertToVar();
  virtual bool addIndex();
  virtual bool allowDataWildcards();
  virtual bool setDataWildcard();
  virtual bool opAssignIndex( const std::string &indexId );
  virtual bool opAbort();
  virtual bool opExitIntens(bool force=false);
  virtual bool opBeep();
  virtual int  opResetError();
  virtual bool opNewCycle();
  virtual int  opDeleteCycle();
  virtual int  opClearCycle();
  virtual int  opFirstCycle();
  virtual int  opLastCycle();
  virtual int  opNextCycle();
  virtual bool opGoCycle();
  virtual int  opGetCycleName();
  virtual int  opSetCycleName();
  virtual int  opUpdateForms();
  virtual bool opSize();
  virtual bool opDataSize();
  virtual bool opIndex();
  virtual bool opIcon();
  virtual bool opCompare(bool bCycle);
  virtual bool opCompose();
  virtual bool opComposeNew();
  virtual bool opComposeIncreaseArg();
  virtual bool opAssignConsistency();
  virtual bool opClass(const std::string &guiElem, const std::string &className);
  virtual bool opSetResource(const std::string &key, const std::string &value, bool useValue);
  virtual bool opSetGuiFieldgroupRange( const std::string &fieldgroupId );
  virtual bool opMessageBox(bool with_title=false);
  virtual int  opGuiElementMethod(std::string guiElem=std::string());
  virtual int  opReplaceGuiElement( const std::string &fgIdOld, const std::string &fgIdNew );
  virtual int  opEndOfFunction();
  virtual int  opBeginTransaction();
  virtual int  opCommitTransaction();
  virtual int  opAbortTransaction();
  virtual bool opAssignValue();
  virtual bool opIncrementValue();
  virtual bool opDecrementValue();
  virtual bool opAccumulateValue();
  virtual bool opActionResult();
  virtual int  opExecuteTask( const std::string &taskId );
  virtual int  opExecuteFunction( const std::string &funcId );
  virtual int  opExecuteFunction( XferDataItem *xferdataitem );
  virtual int  opExecuteProcess( const std::string &processgroupId );
  virtual int  opPluginInitialise( const std::string &pluginId );
  virtual bool opExecutePlugin();
  virtual bool opPluginParameter();
  virtual int  opExecuteJobActionOpen( const std::string &filestreamId);
  virtual int  opGetFileName( const std::string &filestreamId );
  virtual int  opGetBaseName( const std::string &filestreamId );
  virtual int  opGetDirName( const std::string &filestreamId );
  virtual int  opFileDialog( bool dironly );
  virtual bool opFileDialog_setDirname( const::std::string &dirname );
  virtual bool opFileDialog_setFilter( const::std::string &filtername );
  virtual bool opFileDialog_setDirnameXfer();
  virtual bool opFileDialog_setOpenMode(bool open);
  virtual int  opExecuteJobActionXMLXPath( const std::string &filestreamId,
					   XferDataItem *xferdataitemQry,
					   XferDataItem *xferdataitemDest);
  virtual int  fileOption_setXferFilename();
  virtual int  fileOption_setFilename(const std::string& filename);
  virtual int  fileOption_setXferBaseFilename();
  virtual int  fileOption_setBaseFilename(const std::string& filename);
  virtual int  opExecuteJobActionSave( const std::string &filestreamId);
  virtual int  opExecuteJobActionReport( ReportGen::Mode, const std::string &reportId );
  virtual bool opParse( XferDataItem *xferdataitem );
  virtual bool opParse( const std::string& filename );
  virtual bool setSerializeType(AppData::SerializeType);
  virtual bool setSerializeElement( const std::string &elemId );
  virtual bool setSerializeOutputFilename( const std::string &filename );
  virtual int  opSerializeGui();
  virtual int  opSerializeForm( const std::string &formId );
  virtual int  opSerializeGuiElement( const std::string &guiElemId );
  virtual int  opWriteSettings();
  virtual int  opMap(XferDataItem *xferdataitem, int nargs);
  virtual int  opMapForm( const std::string &formId );
  virtual int  opMapFolder( const std::string &folderId, int nargs );
  virtual int  opMapFolderGroup( const std::string &folderGroupId, GuiFolderGroup::OmitMap omit_map );
  virtual int  opMapGuiElement( const std::string &guiElementId );
  virtual int  opMapTableLine( const std::string &tableId );
  virtual int  opUnmap();
  virtual int  opUnmapFolderGroup( const std::string &folderGroupId );
  virtual int  opUnmapForm( const std::string &formId );
  virtual int  opUnmapGuiElement( const std::string &guiElementId );
  virtual int  opUnmapTableLine( const std::string &tableId );
  virtual int  opVisible( XferDataItem *xferdataitem );
  virtual int  opVisibleForm( const std::string &formId );
  virtual int  opVisibleFolderGroup( const std::string &folderGroupId );
  virtual int  opEditable();
  virtual int  opEditable( const std::string &guiElementId );
  virtual int  opAllow();
  virtual int  opDisallow();
  virtual GuiForm      *getForm( const std::string &formId );
  virtual JobTask      *getTask( const std::string &taskId );
  virtual JobFunction  *jobGetFunction( const std::string &funcId );
  virtual ProcessGroup *findProcessGroup( const std::string &pgId );
  virtual int  opEnableGuiElement();
  virtual int  opDisableGuiElement();
  virtual int  opDisableDragGuiElement();
  virtual int  opSetEditable();
  virtual int  opSetEditableCycle();
  virtual int  opSetLocked();
  virtual int  opSetColor();
  virtual int  opSetColorBit();
  virtual int  opUnsetColorBit();
  virtual int  opSetDataTimestamp();
  virtual int  opSetValueTimestamp();
  virtual int  opSetStylesheet();
  virtual int  opSetStylesheet(const std::string &elementId);
  virtual GuiElement   *getNamedElement( const std::string &elementId );
  virtual int  opUpdateGuiElement( const std::string &elementId );
  virtual bool opClearValues();
  virtual bool opEraseValues();
  virtual bool opClearTextWindow( const std::string &textwindow );
  virtual bool opPackValues( int );
  virtual bool opAssignCorresponding();
  virtual bool opGetTimestamp();
  virtual bool opGetDbModified();
  virtual int  opSetDbTimestamp();
  virtual bool opGetClassname();
  virtual bool opGetNodename();
  virtual bool setElseAddress( int nextaddress );
  virtual JobCodeOpIf    *opIfOperator();
  virtual bool opBranch();
  virtual bool setNextAddress( int nextaddress );
  virtual JobCodeOpWhile *opWhileOperator();
  virtual int  opPushReal( const double realvalue );
  virtual int  opPushInteger( const int intvalue );
  virtual int  opPushSortOrder( const std::string &listId );
  virtual int  opPushString( const std::string &stringconst );
  virtual int  opPushEndOfLine();
  virtual int  opPushInvalid();
  virtual int  opPushOldValue();
  virtual int  opPushIndexNumber();
  virtual int  opPushColumn();
  virtual int  opPushRow();
  virtual int  opPushDiagramXPos();
  virtual int  opPushDiagramYPos();
  virtual int  opPushSortCriteria();
  virtual int  opPushError();
  virtual int  opPushReason( JobElement::CallReason reason );
  virtual int  opPushCycle();
  virtual int  opPushMaxCycle();
  virtual int  opPushIndex( const std::string &indexId );
  virtual int  opPushUnits();
  virtual int  opPushLabel();
  virtual bool opPushIndex();
  virtual bool opPushIndexOfLevel();
  virtual bool opEvalValid();
  virtual bool opEvalComplexValue();
  virtual bool opEvalComplexRealValue();
  virtual bool opEvalComplexImagValue();
  virtual bool opEvalAbsValue();
  virtual bool opEvalLengthValue();
  virtual bool opEvalSinValue();
  virtual bool opEvalCosValue();
  virtual bool opEvalTanValue();
  virtual bool opEvalASinValue();
  virtual bool opEvalACosValue();
  virtual bool opEvalATanValue();
  virtual bool opEvalATan2Value();
  virtual bool opEvalLogValue();
  virtual bool opEvalLog10Value();
  virtual bool opEvalSqrtValue();
  virtual bool opEvalArgValue();
  virtual bool opEvalChanged( const std::string &guiElemId, const bool filter );
  virtual bool opRound();
  virtual bool opRound5();
  virtual bool opRound10();
  virtual bool opConfirm(bool cancelBtn);
  virtual bool opGetText();
  virtual bool opAdd();
  virtual bool opSub();
  virtual bool opMul();
  virtual bool opDiv();
  virtual bool opModulo();
  virtual bool opPower();
  virtual bool opNegate();
  virtual bool opGtr();
  virtual bool opGeq();
  virtual bool opLss();
  virtual bool opLeq();
  virtual bool opEql();
  virtual bool opNeq();
  virtual bool opAnd();
  virtual bool opOr();
  virtual bool opNot();
  virtual bool opPrint();
  virtual int opPrintLog();
  virtual int  opLog( const std::string &level );
  virtual bool opLogMsg();
  virtual int  opSetError();
  virtual bool opSetErrorMsg();
  virtual bool opSetMessage();
  virtual bool opMessage();
  // END JOB
  //
  //
  // get-functions
  virtual DataReference         *getDataRef();
  virtual XferDataItem          *getDataItem();
  virtual XferDataItemIndex     *getDataItemIndex();
  virtual int                    getDataLevel();
  virtual FileStream            *getFileStream();
  virtual GuiElement            *getGuiElement();
  virtual GuiDataField          *getGuiDataField();
  virtual GuiVoid               *getGuiVoidField();
  virtual GuiIndex              *getGuiIndexField();
  virtual GuiFieldgroup         *getGuiFieldGroup();
  virtual GuiFieldgroupLine     *getGuiFieldgroupLine();
  virtual GuiLabel              *getGuiLabelField();
  virtual GuiForm               *getGuiForm();
  virtual GuiList               *getGuiList();
  virtual GuiScrolledText       *getGuiScrolledText();
  virtual HelpManager::HelpKey  *getHelpkey();
  virtual ListPlot              *getListplot();
  virtual ListGraph             *getListgraph();
  virtual GuiPlotDataItem       *getGuiPlotaxis();
  virtual Simpel                *getSimpel();
  virtual PSPlot                *getPsPlot();
  virtual PSPlot::PSStream      *getPsStream();
  virtual Gui3dPlot             *getPlot3d();
  virtual Gui2dPlot           *getGui2dPlot();
  virtual Gui2dPlot::PlotItem *getGuiPlotitem();
  virtual Gui2dPlot::PlotItem *getGuiXPlotitem();
  virtual GuiFolder             *getGuiFolder();
  virtual GuiTable              *getGuiTable();
  virtual GuiTableLine          *getGuiTableLine();
  virtual GuiTableSize          *getGuiTablesize();
  virtual GuiTableItem      *getGuiTableDataitem();
  virtual GuiTableItem          *getGuiTableItem();
  virtual Plugin                *getPlugin();
  virtual FileButtonList        *getFilemenulist();
  virtual HardCopyFolder   *getPrintfolder();
  virtual HardCopyListener      *getPrintobject();
  virtual Process               *getProcess();
  virtual ProcessGroup          *getProcessgroup();
  virtual Stream                *getStream();
  virtual int                    getIndexnum();
  virtual ReportStream          *getReportStream();
  virtual JobFunction           *getFunction();
  virtual JobTask               *getTask();
  virtual JobDataReference      *getJobDataRef();
  virtual JobAction             *getJobAction();
  virtual int                    getFunctionNextAddress();
  virtual void                   setFunctionHandler( FunctionHandler * );
protected:
  DataDictionary::DataType getDataType();
  GuiFieldgroup *getFieldgroup();
  // END get-functions

//=============================================================================//
// Representation                                                              //
//=============================================================================//
private:
  std::stack<InterpreterConfigurator_Rep *> m_stack;
  InterpreterConfigurator_Rep *m_rep;
};

#endif
